# jv-store — the JarvisOS app store, declaratively.
#
# CLAUDE.md is absolute: "If it isn't declared, it doesn't exist. No imperative
# installs." A store that ran `nix profile install` would put apps outside the
# flake and break reproducibility. So this store is a FRIENDLY FRONT-END TO THE
# FLAKE, not a package manager:
#
#   click Install  ->  the app's attr name is appended to
#                      /var/lib/jarvis/store/selected.nix (a plain list)
#                   -> `jarvis.apps.extra` reads that list
#                   -> the store runs `nixos-rebuild switch` (pkexec)
#                   -> the app exists, declared, and survives a rebuild from
#                      a clean clone.
#
# The selection file lives OUTSIDE the repo (it is machine state, not source)
# but it is plain text, diffable, and can be copied into the flake verbatim.
{ config, lib, pkgs, ... }:
let
  selectedFile = "/var/lib/jarvis/store/selected.nix";
  # Read the user's picks if the file exists; an empty list before first use.
  selected =
    if builtins.pathExists selectedFile then import selectedFile else [ ];
  # Resolve attr names -> packages, skipping anything nixpkgs no longer has
  # (a rename must never make the machine unbuildable).
  resolve = names: lib.filter (p: p != null) (map (n: pkgs.${n} or null) names);
in
{
  # The store's picks become part of the declared app set.
  jarvis.apps.extra = resolve selected;

  systemd.tmpfiles.rules = [
    "d /var/lib/jarvis/store 0775 root jarvis -"
  ];

  environment.systemPackages = [
    # The store front-end itself: a fuzzel-driven picker over a curated
    # catalog, then a rebuild. Deliberately simple and scriptable — the
    # Quickshell store UI (PLAN E-track) replaces the front-end later, but the
    # mechanism below is the part that must stay honest.
    (pkgs.writeShellApplication {
      name = "jv-store";
      runtimeInputs = with pkgs; [ fuzzel libnotify coreutils gnused gnugrep ];
      text = ''
        set -euo pipefail
        SEL=${selectedFile}
        CATALOG=/etc/jarvis/store-catalog.tsv

        list_installed() { [ -f "$SEL" ] && grep -oE '"[^"]+"' "$SEL" | tr -d '"' || true; }

        # name<TAB>description<TAB>category  ->  one pretty line per app
        pick=$(
          while IFS=$'\t' read -r attr desc cat; do
            [ -z "''${attr:-}" ] && continue
            mark=" "
            if list_installed | grep -qx "$attr"; then mark="✓"; fi
            printf '%s  %-22s %-14s %s\n' "$mark" "$attr" "[$cat]" "$desc"
          done < "$CATALOG" | fuzzel --dmenu --prompt "install >  " --width 88 --lines 20
        ) || exit 0

        attr=$(printf '%s' "$pick" | awk '{print $2}')
        [ -z "$attr" ] && exit 0

        if list_installed | grep -qx "$attr"; then
          notify-send "JarvisOS store" "$attr is already installed." || true
          exit 0
        fi

        notify-send "JarvisOS store" "Adding $attr — rebuilding…" || true

        # Append to the declared selection, then rebuild. pkexec so the user
        # authenticates once, in the desktop's own dialog.
        tmp=$(mktemp)
        {
          echo "# Generated by jv-store. Apps chosen in the store, kept DECLARED."
          echo "["
          { list_installed; echo "$attr"; } | sort -u | sed 's/^/  "/; s/$/"/'
          echo "]"
        } > "$tmp"

        pkexec install -Dm0664 -o root -g jarvis "$tmp" "$SEL"
        rm -f "$tmp"

        if pkexec nixos-rebuild switch --flake /home/ofek/jarvisos#ares; then
          notify-send "JarvisOS store" "$attr installed." || true
        else
          notify-send -u critical "JarvisOS store" "Rebuild failed — $attr not installed. The previous generation is untouched." || true
        fi
      '';
    })
  ];

  # The catalog the store offers. Plain TSV so adding an app is a one-line
  # change and the loop can extend it safely.
  environment.etc."jarvis/store-catalog.tsv".text = ''
    firefox	Web browser (native Wayland)	web
    chromium	Chromium browser	web
    thunderbird	Mail client	web
    telegram-desktop	Telegram messenger	comms
    signal-desktop	Signal messenger	comms
    discord	Discord chat	comms
    element-desktop	Matrix client	comms
    slack	Slack	comms
    zoom-us	Zoom meetings	comms
    libreoffice-fresh	Office suite	office
    onlyoffice-bin	ONLYOFFICE suite	office
    obsidian	Markdown notes	office
    logseq	Outliner notes	office
    zotero	Reference manager	office
    calibre	E-book library	office
    gimp	Image editor	creative
    inkscape	Vector graphics	creative
    krita	Digital painting	creative
    blender	3D creation	creative
    darktable	RAW photo workflow	creative
    rawtherapee	RAW developer	creative
    shotcut	Video editor	creative
    kdenlive	Video editor	creative
    obs-studio	Streaming and recording	creative
    audacity	Audio editor	creative
    ardour	Digital audio workstation	creative
    musescore	Music notation	creative
    handbrake	Video transcoder	creative
    vlc	Media player	media
    mpv	Minimal media player	media
    spotify	Spotify client	media
    rhythmbox	Music library	media
    vscode	Visual Studio Code	dev
    jetbrains.idea-community	IntelliJ IDEA CE	dev
    jetbrains.pycharm-community	PyCharm CE	dev
    android-studio	Android Studio	dev
    neovim	Modal editor	dev
    helix	Modal editor	dev
    zed-editor	Zed editor	dev
    lazygit	Git TUI	dev
    docker	Containers	dev
    podman	Containers (rootless)	dev
    postman	API client	dev
    insomnia	API client	dev
    dbeaver-bin	Database GUI	dev
    wireshark	Network analyzer	dev
    virt-manager	Virtual machines	dev
    steam	Steam games	games
    lutris	Game launcher	games
    heroic	Epic/GOG launcher	games
    prismlauncher	Minecraft launcher	games
    mangohud	In-game overlay	games
    gamemode	Game performance daemon	games
    keepassxc	Password manager	utils
    bitwarden	Password manager	utils
    syncthing	File sync	utils
    nextcloud-client	Nextcloud sync	utils
    filezilla	FTP client	utils
    qbittorrent	Torrent client	utils
    gparted	Partition editor	utils
    remmina	Remote desktop	utils
    flameshot	Screenshot tool	utils
    peek	GIF recorder	utils
    czkawka	Duplicate finder	utils
    localsend	Local file sharing	utils
  '';
}
