//! GENERATED by tools/gen_bindings.py from schemas/*.json — DO NOT EDIT.
#![allow(dead_code)]

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

pub const TOPIC_AUDIO_TRANSCRIPT: &str = "audio.transcript";
pub const V_AUDIO_TRANSCRIPT: u32 = 1;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AudioTranscriptWord {
    pub w: String,
    pub t0: f64,
    pub t1: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub p: Option<f64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AudioTranscriptKind {
    Partial,
    Final,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AudioTranscript {
    pub kind: AudioTranscriptKind,
    pub utterance_id: String,
    pub text: String,
    pub lang: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub t0: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub t1: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub words: Option<Vec<AudioTranscriptWord>>,
}

pub const TOPIC_AUDIO_VAD: &str = "audio.vad";
pub const V_AUDIO_VAD: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AudioVadEvent {
    SpeechStart,
    SpeechEnd,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AudioVad {
    pub event: AudioVadEvent,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub utterance_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_s: Option<f64>,
}

pub const TOPIC_AUDIO_WAKE: &str = "audio.wake";
pub const V_AUDIO_WAKE: u32 = 1;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AudioWake {
    pub model: String,
    pub score: f64,
    pub threshold: f64,
}

pub const TOPIC_BRAIN_REQUEST: &str = "brain.request";
pub const V_BRAIN_REQUEST: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BrainRequestSource {
    Voice,
    Cli,
    Replay,
    System,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BrainRequest {
    pub text: String,
    pub source: BrainRequestSource,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub utterance_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub speak: Option<bool>,
}

pub const TOPIC_BRAIN_RESPONSE: &str = "brain.response";
pub const V_BRAIN_RESPONSE: u32 = 1;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BrainResponseInReplyTo {
    pub src: String,
    pub seq: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BrainResponseFinishReason {
    Stop,
    Length,
    Error,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BrainResponseBackend {
    Gpu,
    Cpu,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BrainResponse {
    pub text: String,
    pub finish_reason: BrainResponseFinishReason,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub in_reply_to: Option<BrainResponseInReplyTo>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub utterance_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend: Option<BrainResponseBackend>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latency_ms: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Envelope {
    pub topic: String,
    pub ts: f64,
    pub seq: u64,
    pub src: String,
    pub conf: f64,
    pub v: u64,
    pub body: rmpv::Value,
}

pub const TOPIC_SPEECH_SAY: &str = "speech.say";
pub const V_SPEECH_SAY: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SpeechSayPriority {
    Low,
    Normal,
    Urgent,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SpeechSay {
    pub text: String,
    pub say_id: String,
    pub in_reply_to_utterance: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub priority: Option<SpeechSayPriority>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interruptible: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub voice: Option<String>,
}

pub const TOPIC_SPEECH_STATE: &str = "speech.state";
pub const V_SPEECH_STATE: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SpeechStateState {
    Idle,
    Speaking,
    Interrupted,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SpeechStateReason {
    Completed,
    Wake,
    Preempted,
    Error,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SpeechState {
    pub state: SpeechStateState,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub say_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<SpeechStateReason>,
}

pub const TOPIC_SYS_HEALTH: &str = "sys.health";
pub const V_SYS_HEALTH: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SysHealthState {
    Starting,
    Ok,
    Degraded,
    Error,
    Stopping,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SysHealth {
    pub service: String,
    pub state: SysHealthState,
    pub uptime_s: f64,
    pub period_s: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub drops: Option<BTreeMap<String, u64>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metrics: Option<BTreeMap<String, f64>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}
