//! GENERATED by tools/gen_bindings.py from schemas/*.json — DO NOT EDIT.
#![allow(dead_code)]

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

pub const TOPIC_ACTION_CONFIRM: &str = "action.confirm";
pub const V_ACTION_CONFIRM: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ActionConfirmKind {
    Request,
    Answer,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ActionConfirmAnsweredBy {
    Voice,
    Cli,
    Timeout,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ActionConfirm {
    pub kind: ActionConfirmKind,
    pub request_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub window_s: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub granted: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub answered_by: Option<ActionConfirmAnsweredBy>,
}

pub const TOPIC_ACTION_RESULT: &str = "action.result";
pub const V_ACTION_RESULT: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ActionResultError {
    UnknownTool,
    InvalidArgs,
    CapabilityMismatch,
    Denied,
    ConfirmTimeout,
    ExecutionFailed,
    Timeout,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ActionResult {
    pub request_id: String,
    pub ok: bool,
    pub duration_ms: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<rmpv::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<ActionResultError>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

pub const TOPIC_AUDIO_TRANSCRIPT: &str = "audio.transcript";
pub const V_AUDIO_TRANSCRIPT: u32 = 1;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AudioTranscriptWord {
    pub w: String,
    pub t0: f64,
    pub t1: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub p: Option<f64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AudioTranscriptKind {
    Partial,
    Final,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AudioTranscript {
    pub kind: AudioTranscriptKind,
    pub utterance_id: String,
    pub text: String,
    pub lang: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub t0: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub t1: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub words: Option<Vec<AudioTranscriptWord>>,
}

pub const TOPIC_AUDIO_VAD: &str = "audio.vad";
pub const V_AUDIO_VAD: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AudioVadEvent {
    SpeechStart,
    SpeechEnd,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AudioVad {
    pub event: AudioVadEvent,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub utterance_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_s: Option<f64>,
}

pub const TOPIC_AUDIO_WAKE: &str = "audio.wake";
pub const V_AUDIO_WAKE: u32 = 1;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AudioWake {
    pub model: String,
    pub score: f64,
    pub threshold: f64,
}

pub const TOPIC_BRAIN_REQUEST: &str = "brain.request";
pub const V_BRAIN_REQUEST: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BrainRequestSource {
    Voice,
    Cli,
    Replay,
    System,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BrainRequest {
    pub text: String,
    pub source: BrainRequestSource,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub utterance_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub speak: Option<bool>,
}

pub const TOPIC_BRAIN_RESPONSE: &str = "brain.response";
pub const V_BRAIN_RESPONSE: u32 = 1;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BrainResponseInReplyTo {
    pub src: String,
    pub seq: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BrainResponseFinishReason {
    Stop,
    Length,
    Error,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BrainResponseBackend {
    Gpu,
    Cpu,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BrainResponse {
    pub text: String,
    pub finish_reason: BrainResponseFinishReason,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub in_reply_to: Option<BrainResponseInReplyTo>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub utterance_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend: Option<BrainResponseBackend>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latency_ms: Option<f64>,
}

pub const TOPIC_COMPAT_INSTALL: &str = "compat.install";
pub const V_COMPAT_INSTALL: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CompatInstallEvent {
    Fingerprinted,
    Screened,
    PrefixCreated,
    Installed,
    Failed,
    Blocked,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CompatInstallInstaller {
    Nsis,
    Inno,
    Msi,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CompatInstallArch {
    X86,
    X64,
    Arm64,
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CompatInstall {
    pub event: CompatInstallEvent,
    pub app: String,
    pub sha256: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub installer: Option<CompatInstallInstaller>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arch: Option<CompatInstallArch>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recipe: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

pub const TOPIC_CONTEXT_SYSTEM: &str = "context.system";
pub const V_CONTEXT_SYSTEM: u32 = 1;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ContextSystem {
    pub net_online: bool,
    pub load1: f64,
    pub mem_used_pct: f64,
    pub audio_volume: f64,
    pub audio_muted: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub battery_pct: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gpu_vram_free_mb: Option<f64>,
}

pub const TOPIC_CONTEXT_WINDOW: &str = "context.window";
pub const V_CONTEXT_WINDOW: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ContextWindowKind {
    FocusChanged,
    Opened,
    Closed,
    TitleChanged,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ContextWindow {
    pub kind: ContextWindowKind,
    pub window_id: u64,
    pub app_id: String,
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workspace: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub monitor: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub focused: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub redacted: Option<bool>,
}

pub const TOPIC_DIALOG_LISTEN: &str = "dialog.listen";
pub const V_DIALOG_LISTEN: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DialogListenReason {
    Confirm,
    Onboarding,
    Followup,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DialogListen {
    pub listen_id: String,
    pub window_s: f64,
    pub reason: DialogListenReason,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Envelope {
    pub topic: String,
    pub ts: f64,
    pub seq: u64,
    pub src: String,
    pub conf: f64,
    pub v: u64,
    pub body: rmpv::Value,
}

pub const TOPIC_GUARD_VERDICT: &str = "guard.verdict";
pub const V_GUARD_VERDICT: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GuardVerdictVerdict {
    Clean,
    Suspicious,
    Blocked,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GuardVerdict {
    pub sha256: String,
    pub verdict: GuardVerdictVerdict,
    pub reasons: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scanned_by: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

pub const TOPIC_INTENT_ACTION: &str = "intent.action";
pub const V_INTENT_ACTION: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum IntentActionCapability {
    Observe,
    Benign,
    Destructive,
    Privileged,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct IntentAction {
    pub request_id: String,
    pub tool: String,
    pub args: rmpv::Value,
    pub capability: IntentActionCapability,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub needs_confirmation: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub utterance_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
}

pub const TOPIC_SPEECH_SAY: &str = "speech.say";
pub const V_SPEECH_SAY: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SpeechSayPriority {
    Low,
    Normal,
    Urgent,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SpeechSay {
    pub text: String,
    pub say_id: String,
    pub in_reply_to_utterance: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub priority: Option<SpeechSayPriority>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interruptible: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub voice: Option<String>,
}

pub const TOPIC_SPEECH_STATE: &str = "speech.state";
pub const V_SPEECH_STATE: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SpeechStateState {
    Idle,
    Speaking,
    Interrupted,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SpeechStateReason {
    Completed,
    Wake,
    Preempted,
    Error,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SpeechState {
    pub state: SpeechStateState,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub say_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<SpeechStateReason>,
}

pub const TOPIC_SYS_HEALTH: &str = "sys.health";
pub const V_SYS_HEALTH: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SysHealthState {
    Starting,
    Ok,
    Degraded,
    Error,
    Stopping,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SysHealth {
    pub service: String,
    pub state: SysHealthState,
    pub uptime_s: f64,
    pub period_s: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub drops: Option<BTreeMap<String, u64>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metrics: Option<BTreeMap<String, f64>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}
