// GENERATED by tools/gen_sessions_qml.py from harness/fixtures/sessions/*.jsonl — DO NOT EDIT.
//
// Every recorded perception session in harness/fixtures/sessions, as the
// exact JSONL lines committed there: `header` is the session header and
// `frames` are the envelopes jv-ears published, in order, unmodified.
//
// The HUD's tests replay these through core/BusModel to assert what the
// elements do with perception's REAL output instead of with frames typed
// by whoever wrote the expectation (PLAN B9). tst_sessionreplay.qml is
// the reader; harness/fixtures/sessions/README.md is the recording.
import QtQuick

QtObject {
  // Every recording here, sorted. A test asserts this list is complete,
  // so a fixture that silently stops being compiled in is a failure and
  // not a suite that quietly got smaller.
  readonly property var names: ["hey-jarvis-clean", "hey-jarvis-music", "hey-jarvis-pause", "speech-no-wake"]

  // name -> { header: string, frames: [string] }
  readonly property var byName: ({
    "hey-jarvis-clean": {
      "header": "{\"boot_id\": \"sample-clock\", \"wall_time_utc\": \"2026-09-24T02:47:50+00:00\", \"monotonic_now\": 0.0}",
      "frames": [
        "{\"topic\": \"audio.vad\", \"ts\": 0.8, \"seq\": 0, \"src\": \"jv-ears\", \"conf\": 1.0, \"v\": 1, \"body\": {\"event\": \"speech_start\", \"utterance_id\": \"5ab8fecf-13d0-4f86-aa5d-0b2cc23b4d5d\"}}",
        "{\"topic\": \"audio.wake\", \"ts\": 1.44, \"seq\": 0, \"src\": \"jv-ears\", \"conf\": 0.990387, \"v\": 1, \"body\": {\"model\": \"hey_jarvis\", \"score\": 0.9903865456581116, \"threshold\": 0.5}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 2.16, \"seq\": 0, \"src\": \"jv-ears\", \"conf\": 0.909553, \"v\": 1, \"body\": {\"kind\": \"partial\", \"utterance_id\": \"5ab8fecf-13d0-4f86-aa5d-0b2cc23b4d5d\", \"text\": \"Hey Jarvis, what time is it?\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 2.04}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 2.88, \"seq\": 1, \"src\": \"jv-ears\", \"conf\": 0.887654, \"v\": 1, \"body\": {\"kind\": \"partial\", \"utterance_id\": \"5ab8fecf-13d0-4f86-aa5d-0b2cc23b4d5d\", \"text\": \"Hey Jarvis, what time is it?\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 2.76}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 3.6, \"seq\": 2, \"src\": \"jv-ears\", \"conf\": 0.892123, \"v\": 1, \"body\": {\"kind\": \"partial\", \"utterance_id\": \"5ab8fecf-13d0-4f86-aa5d-0b2cc23b4d5d\", \"text\": \"Hey Jarvis, what time is it?\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 3.48}}",
        "{\"topic\": \"audio.vad\", \"ts\": 3.76, \"seq\": 1, \"src\": \"jv-ears\", \"conf\": 1.0, \"v\": 1, \"body\": {\"event\": \"speech_end\", \"utterance_id\": \"5ab8fecf-13d0-4f86-aa5d-0b2cc23b4d5d\", \"duration_s\": 2.96}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 3.76, \"seq\": 3, \"src\": \"jv-ears\", \"conf\": 0.88583, \"v\": 1, \"body\": {\"kind\": \"final\", \"utterance_id\": \"5ab8fecf-13d0-4f86-aa5d-0b2cc23b4d5d\", \"text\": \"Hey Jarvis, what time is it?\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 3.56, \"words\": [{\"w\": \"Hey\", \"t0\": 0.0, \"t1\": 0.6, \"p\": 0.9400274753570557}, {\"w\": \"Jarvis,\", \"t0\": 0.6, \"t1\": 1.1, \"p\": 0.9623562097549438}, {\"w\": \"what\", \"t0\": 1.4, \"t1\": 1.44, \"p\": 0.9784973859786987}, {\"w\": \"time\", \"t0\": 1.44, \"t1\": 1.64, \"p\": 0.9958745837211609}, {\"w\": \"is\", \"t0\": 1.64, \"t1\": 1.82, \"p\": 0.9962723255157471}, {\"w\": \"it?\", \"t0\": 1.82, \"t1\": 2.02, \"p\": 0.9974240064620972}]}}"
      ]
    },
    "hey-jarvis-music": {
      "header": "{\"boot_id\": \"sample-clock\", \"wall_time_utc\": \"2026-09-24T02:48:00+00:00\", \"monotonic_now\": 0.0}",
      "frames": [
        "{\"topic\": \"audio.vad\", \"ts\": 0.8, \"seq\": 0, \"src\": \"jv-ears\", \"conf\": 1.0, \"v\": 1, \"body\": {\"event\": \"speech_start\", \"utterance_id\": \"7f078430-0e3a-4ca6-99b6-7d1a52ed72a8\"}}",
        "{\"topic\": \"audio.wake\", \"ts\": 1.44, \"seq\": 0, \"src\": \"jv-ears\", \"conf\": 0.963005, \"v\": 1, \"body\": {\"model\": \"hey_jarvis\", \"score\": 0.9630050659179688, \"threshold\": 0.5}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 2.16, \"seq\": 0, \"src\": \"jv-ears\", \"conf\": 0.876775, \"v\": 1, \"body\": {\"kind\": \"partial\", \"utterance_id\": \"7f078430-0e3a-4ca6-99b6-7d1a52ed72a8\", \"text\": \"Hey Jarvis turn to volume\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 2.04}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 2.88, \"seq\": 1, \"src\": \"jv-ears\", \"conf\": 0.713505, \"v\": 1, \"body\": {\"kind\": \"partial\", \"utterance_id\": \"7f078430-0e3a-4ca6-99b6-7d1a52ed72a8\", \"text\": \"Hey Jarvis, turn the volume down.\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 2.76}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 3.6, \"seq\": 2, \"src\": \"jv-ears\", \"conf\": 0.742816, \"v\": 1, \"body\": {\"kind\": \"partial\", \"utterance_id\": \"7f078430-0e3a-4ca6-99b6-7d1a52ed72a8\", \"text\": \"Hey Jarvis, turn the volume down!\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 3.48}}",
        "{\"topic\": \"audio.vad\", \"ts\": 4.16, \"seq\": 1, \"src\": \"jv-ears\", \"conf\": 1.0, \"v\": 1, \"body\": {\"event\": \"speech_end\", \"utterance_id\": \"7f078430-0e3a-4ca6-99b6-7d1a52ed72a8\", \"duration_s\": 3.36}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 4.16, \"seq\": 3, \"src\": \"jv-ears\", \"conf\": 0.739424, \"v\": 1, \"body\": {\"kind\": \"final\", \"utterance_id\": \"7f078430-0e3a-4ca6-99b6-7d1a52ed72a8\", \"text\": \"Hey Jarvis, turn the volume down.\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 3.96, \"words\": [{\"w\": \"Hey\", \"t0\": 0.0, \"t1\": 0.64, \"p\": 0.9168547987937927}, {\"w\": \"Jarvis,\", \"t0\": 0.64, \"t1\": 1.18, \"p\": 0.9431862831115723}, {\"w\": \"turn\", \"t0\": 1.4, \"t1\": 1.56, \"p\": 0.9127002358436584}, {\"w\": \"the\", \"t0\": 1.56, \"t1\": 1.7, \"p\": 0.9877946376800537}, {\"w\": \"volume\", \"t0\": 1.7, \"t1\": 2.02, \"p\": 0.9914496541023254}, {\"w\": \"down.\", \"t0\": 2.02, \"t1\": 2.36, \"p\": 0.9974464178085327}]}}"
      ]
    },
    "hey-jarvis-pause": {
      "header": "{\"boot_id\": \"sample-clock\", \"wall_time_utc\": \"2026-09-24T02:48:18+00:00\", \"monotonic_now\": 0.0}",
      "frames": [
        "{\"topic\": \"audio.vad\", \"ts\": 0.8, \"seq\": 0, \"src\": \"jv-ears\", \"conf\": 1.0, \"v\": 1, \"body\": {\"event\": \"speech_start\", \"utterance_id\": \"a3841013-f8fb-409d-a676-9b22cd443208\"}}",
        "{\"topic\": \"audio.wake\", \"ts\": 1.36, \"seq\": 0, \"src\": \"jv-ears\", \"conf\": 0.879226, \"v\": 1, \"body\": {\"model\": \"hey_jarvis\", \"score\": 0.8792257308959961, \"threshold\": 0.5}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 2.08, \"seq\": 0, \"src\": \"jv-ears\", \"conf\": 0.874028, \"v\": 1, \"body\": {\"kind\": \"partial\", \"utterance_id\": \"a3841013-f8fb-409d-a676-9b22cd443208\", \"text\": \"Hey Jarvis remind me to\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 1.96}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 2.8, \"seq\": 1, \"src\": \"jv-ears\", \"conf\": 0.832917, \"v\": 1, \"body\": {\"kind\": \"partial\", \"utterance_id\": \"a3841013-f8fb-409d-a676-9b22cd443208\", \"text\": \"Hey Jarvis, remind me too.\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 2.68}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 3.52, \"seq\": 2, \"src\": \"jv-ears\", \"conf\": 0.845586, \"v\": 1, \"body\": {\"kind\": \"partial\", \"utterance_id\": \"a3841013-f8fb-409d-a676-9b22cd443208\", \"text\": \"Hey Jarvis remind me to\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 3.4}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 4.24, \"seq\": 3, \"src\": \"jv-ears\", \"conf\": 0.840684, \"v\": 1, \"body\": {\"kind\": \"partial\", \"utterance_id\": \"a3841013-f8fb-409d-a676-9b22cd443208\", \"text\": \"Hey Jarvis remind me to Call my sister\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 4.12}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 4.96, \"seq\": 4, \"src\": \"jv-ears\", \"conf\": 0.88488, \"v\": 1, \"body\": {\"kind\": \"partial\", \"utterance_id\": \"a3841013-f8fb-409d-a676-9b22cd443208\", \"text\": \"Hey Jarvis remind me to Call my sister tomorrow morning\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 4.84}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 5.68, \"seq\": 5, \"src\": \"jv-ears\", \"conf\": 0.867285, \"v\": 1, \"body\": {\"kind\": \"partial\", \"utterance_id\": \"a3841013-f8fb-409d-a676-9b22cd443208\", \"text\": \"Hey Jarvis remind me to Call my sister tomorrow morning\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 5.56}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 6.4, \"seq\": 6, \"src\": \"jv-ears\", \"conf\": 0.843416, \"v\": 1, \"body\": {\"kind\": \"partial\", \"utterance_id\": \"a3841013-f8fb-409d-a676-9b22cd443208\", \"text\": \"Hey Jarvis, remind me to. Call my sister tomorrow morning.\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 6.28}}",
        "{\"topic\": \"audio.vad\", \"ts\": 6.64, \"seq\": 1, \"src\": \"jv-ears\", \"conf\": 1.0, \"v\": 1, \"body\": {\"event\": \"speech_end\", \"utterance_id\": \"a3841013-f8fb-409d-a676-9b22cd443208\", \"duration_s\": 5.84}}",
        "{\"topic\": \"audio.transcript\", \"ts\": 6.64, \"seq\": 7, \"src\": \"jv-ears\", \"conf\": 0.863412, \"v\": 1, \"body\": {\"kind\": \"final\", \"utterance_id\": \"a3841013-f8fb-409d-a676-9b22cd443208\", \"text\": \"Hey Jarvis remind me to Call my sister tomorrow morning\", \"lang\": \"en\", \"t0\": 0.0, \"t1\": 6.44, \"words\": [{\"w\": \"Hey\", \"t0\": 0.0, \"t1\": 0.58, \"p\": 0.9392139315605164}, {\"w\": \"Jarvis\", \"t0\": 0.58, \"t1\": 1.08, \"p\": 0.9683322310447693}, {\"w\": \"remind\", \"t0\": 1.08, \"t1\": 1.54, \"p\": 0.3852539360523224}, {\"w\": \"me\", \"t0\": 1.54, \"t1\": 1.78, \"p\": 0.994889497756958}, {\"w\": \"to\", \"t0\": 1.78, \"t1\": 2.2199999999999998, \"p\": 0.9024999737739563}, {\"w\": \"Call\", \"t0\": 2.76, \"t1\": 3.52, \"p\": 0.18894962966442108}, {\"w\": \"my\", \"t0\": 3.52, \"t1\": 3.74, \"p\": 0.9950520396232605}, {\"w\": \"sister\", \"t0\": 3.74, \"t1\": 4.1, \"p\": 0.9985643029212952}, {\"w\": \"tomorrow\", \"t0\": 4.1, \"t1\": 4.52, \"p\": 0.9948187470436096}, {\"w\": \"morning\", \"t0\": 4.52, \"t1\": 4.92, \"p\": 0.9965445399284363}]}}"
      ]
    },
    "speech-no-wake": {
      "header": "{\"boot_id\": \"sample-clock\", \"wall_time_utc\": \"2026-09-24T02:48:18+00:00\", \"monotonic_now\": 0.0}",
      "frames": [
        "{\"topic\": \"audio.vad\", \"ts\": 0.8, \"seq\": 0, \"src\": \"jv-ears\", \"conf\": 1.0, \"v\": 1, \"body\": {\"event\": \"speech_start\", \"utterance_id\": \"2c45a229-b9c0-4423-9f90-69f61ba6dc10\"}}",
        "{\"topic\": \"audio.vad\", \"ts\": 4.4, \"seq\": 1, \"src\": \"jv-ears\", \"conf\": 1.0, \"v\": 1, \"body\": {\"event\": \"speech_end\", \"utterance_id\": \"2c45a229-b9c0-4423-9f90-69f61ba6dc10\", \"duration_s\": 3.6}}"
      ]
    }
  })
}
