// GENERATED by tools/gen_theme_qml.py from personality/theme.toml — DO NOT EDIT.
//
// The §06 design tokens, as the one thing every HUD element reads. If you
// are about to type a hex code into a QML file: don't — put it in
// personality/theme.toml and regenerate. The look is versioned with the
// voice and the wake word (invariant 9), and it is diffable in one place.
pragma Singleton
import QtQuick

QtObject {
  // Colour. Ember means Jarvis is doing something — spend it sparingly (§06).
  readonly property color groundDeep: "#090D12"
  readonly property color ground: "#0C1116"
  readonly property color surface: "#141B21"
  readonly property color surface2: "#1C252C"
  readonly property color line: "#2A353D"
  readonly property color lineSoft: "#212B32"
  readonly property color text: "#E4EAEE"
  readonly property color text2: "#9FADB7"
  readonly property color text3: "#6E7E89"
  readonly property color ember: "#F0714A"
  readonly property color emberSoft: "#2A1710"
  readonly property color teal: "#4FB8BF"
  readonly property color tealSoft: "#0F2326"
  readonly property color ok: "#5BC08D"
  readonly property color warn: "#D9A441"
  readonly property color risk: "#E8756B"

  // Type. Sizes are px at 1x; tracking is em, so multiply by the size.
  readonly property string familySans: "Archivo"
  readonly property string familyMono: "JetBrains Mono"
  readonly property int labelPx: 11
  readonly property int bodyPx: 13
  readonly property int readoutPx: 17
  readonly property real labelTrackingEm: 0.14

  // Motion. Every duration is a signal settling, never decoration.
  readonly property bool reducedMotion: false
  readonly property int easeMs: 200
  readonly property int fadeInMs: 120
  readonly property int fadeOutMs: 180
  readonly property int pulseMs: 1600

  // Geometry. The rhythm of a docked plate.
  readonly property int insetPx: 16
  readonly property int gapPx: 8
  readonly property int padPx: 10
  readonly property int radiusPx: 4
  readonly property int hairlinePx: 1
  readonly property real plateOpacity: 0.86
}
