"""GENERATED by tools/gen_bindings.py from schemas/*.json — DO NOT EDIT."""

# flake8: noqa
from __future__ import annotations

import dataclasses
import typing
from typing import Any, ClassVar, Dict, FrozenSet, List, Literal, Optional


@dataclasses.dataclass
class AudioTranscriptWord:
    w: str
    t0: float
    t1: float
    p: Optional[float] = None
    _optional: ClassVar[FrozenSet[str]] = frozenset(['p'])


@dataclasses.dataclass
class AudioTranscript:
    kind: Literal["partial", "final"]
    utterance_id: str
    text: str
    lang: str
    t0: Optional[float] = None
    t1: Optional[float] = None
    words: Optional[List["AudioTranscriptWord"]] = None
    TOPIC: ClassVar[str] = "audio.transcript"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['t0', 't1', 'words'])


@dataclasses.dataclass
class AudioVad:
    event: Literal["speech_start", "speech_end"]
    utterance_id: Optional[str] = None
    duration_s: Optional[float] = None
    TOPIC: ClassVar[str] = "audio.vad"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['duration_s', 'utterance_id'])


@dataclasses.dataclass
class AudioWake:
    model: str
    score: float
    threshold: float
    TOPIC: ClassVar[str] = "audio.wake"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset([])


@dataclasses.dataclass
class BrainRequest:
    text: str
    source: Literal["voice", "cli", "replay", "system"]
    conversation_id: Optional[str] = None
    utterance_id: Optional[str] = None
    speak: Optional[bool] = None
    TOPIC: ClassVar[str] = "brain.request"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['conversation_id', 'speak', 'utterance_id'])


@dataclasses.dataclass
class BrainResponseInReplyTo:
    src: str
    seq: int
    _optional: ClassVar[FrozenSet[str]] = frozenset([])


@dataclasses.dataclass
class BrainResponse:
    text: str
    finish_reason: Literal["stop", "length", "error"]
    conversation_id: Optional[str] = None
    in_reply_to: Optional["BrainResponseInReplyTo"] = None
    utterance_id: Optional[str] = None
    model: Optional[str] = None
    backend: Optional[Literal["gpu", "cpu"]] = None
    latency_ms: Optional[float] = None
    TOPIC: ClassVar[str] = "brain.response"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['backend', 'conversation_id', 'in_reply_to', 'latency_ms', 'model', 'utterance_id'])


@dataclasses.dataclass
class Envelope:
    topic: str
    ts: float
    seq: int
    src: str
    conf: float
    v: int
    body: Dict[str, Any]
    _optional: ClassVar[FrozenSet[str]] = frozenset([])


@dataclasses.dataclass
class SpeechSay:
    text: str
    say_id: str
    in_reply_to_utterance: Optional[str]
    priority: Optional[Literal["low", "normal", "urgent"]] = None
    interruptible: Optional[bool] = None
    voice: Optional[str] = None
    TOPIC: ClassVar[str] = "speech.say"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['interruptible', 'priority', 'voice'])


@dataclasses.dataclass
class SpeechState:
    state: Literal["idle", "speaking", "interrupted"]
    say_id: Optional[str] = None
    reason: Optional[Literal["completed", "wake", "preempted", "error"]] = None
    TOPIC: ClassVar[str] = "speech.state"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['reason', 'say_id'])


@dataclasses.dataclass
class SysHealth:
    service: str
    state: Literal["starting", "ok", "degraded", "error", "stopping"]
    uptime_s: float
    period_s: float
    drops: Optional[Dict[str, int]] = None
    metrics: Optional[Dict[str, float]] = None
    notes: Optional[str] = None
    TOPIC: ClassVar[str] = "sys.health"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['drops', 'metrics', 'notes'])


def to_body(obj: Any) -> Dict[str, Any]:
    """Dataclass -> wire dict. Optional-and-absent fields are omitted
    (closed schemas reject null for them); required-nullable stay null."""
    out: Dict[str, Any] = {}
    for f in dataclasses.fields(obj):
        v = getattr(obj, f.name)
        if v is None and f.name in type(obj)._optional:
            continue
        if dataclasses.is_dataclass(v):
            v = to_body(v)
        elif isinstance(v, list):
            v = [to_body(x) if dataclasses.is_dataclass(x) else x for x in v]
        out[f.name] = v
    return out


def from_body(cls: type, body: Dict[str, Any]) -> Any:
    """Wire dict -> dataclass, recursing into nested dataclass fields."""
    hints = typing.get_type_hints(cls)
    kwargs: Dict[str, Any] = {}
    for f in dataclasses.fields(cls):
        if f.name not in body:
            continue
        v = body[f.name]
        t = hints[f.name]
        if typing.get_origin(t) is typing.Union:  # Optional[X]
            args = [a for a in typing.get_args(t) if a is not type(None)]
            t = args[0] if args else t
        if dataclasses.is_dataclass(t) and isinstance(v, dict):
            v = from_body(t, v)
        elif typing.get_origin(t) is list:
            (item,) = typing.get_args(t)
            if dataclasses.is_dataclass(item):
                v = [from_body(item, x) for x in v]
        kwargs[f.name] = v
    return cls(**kwargs)
