"""GENERATED by tools/gen_bindings.py from schemas/*.json — DO NOT EDIT."""

# flake8: noqa
from __future__ import annotations

import dataclasses
import typing
from typing import Any, ClassVar, Dict, FrozenSet, List, Literal, Optional


@dataclasses.dataclass
class ActionConfirm:
    kind: Literal["request", "answer"]
    request_id: str
    tool: Optional[str] = None
    summary: Optional[str] = None
    window_s: Optional[float] = None
    granted: Optional[bool] = None
    answered_by: Optional[Literal["voice", "cli", "timeout"]] = None
    TOPIC: ClassVar[str] = "action.confirm"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['answered_by', 'granted', 'summary', 'tool', 'window_s'])


@dataclasses.dataclass
class ActionResult:
    request_id: str
    ok: bool
    duration_ms: float
    output: Optional[str] = None
    data: Optional[Dict[str, Any]] = None
    error: Optional[Literal["unknown_tool", "invalid_args", "capability_mismatch", "denied", "confirm_timeout", "execution_failed", "timeout"]] = None
    detail: Optional[str] = None
    TOPIC: ClassVar[str] = "action.result"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['data', 'detail', 'error', 'output'])


@dataclasses.dataclass
class AudioTranscriptWord:
    w: str
    t0: float
    t1: float
    p: Optional[float] = None
    _optional: ClassVar[FrozenSet[str]] = frozenset(['p'])


@dataclasses.dataclass
class AudioTranscript:
    kind: Literal["partial", "final"]
    utterance_id: str
    text: str
    lang: str
    t0: Optional[float] = None
    t1: Optional[float] = None
    words: Optional[List["AudioTranscriptWord"]] = None
    TOPIC: ClassVar[str] = "audio.transcript"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['t0', 't1', 'words'])


@dataclasses.dataclass
class AudioVad:
    event: Literal["speech_start", "speech_end"]
    utterance_id: Optional[str] = None
    duration_s: Optional[float] = None
    TOPIC: ClassVar[str] = "audio.vad"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['duration_s', 'utterance_id'])


@dataclasses.dataclass
class AudioWake:
    model: str
    score: float
    threshold: float
    TOPIC: ClassVar[str] = "audio.wake"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset([])


@dataclasses.dataclass
class BrainRequest:
    text: str
    source: Literal["voice", "cli", "replay", "system"]
    conversation_id: Optional[str] = None
    utterance_id: Optional[str] = None
    speak: Optional[bool] = None
    TOPIC: ClassVar[str] = "brain.request"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['conversation_id', 'speak', 'utterance_id'])


@dataclasses.dataclass
class BrainResponseInReplyTo:
    src: str
    seq: int
    _optional: ClassVar[FrozenSet[str]] = frozenset([])


@dataclasses.dataclass
class BrainResponse:
    text: str
    finish_reason: Literal["stop", "length", "error"]
    conversation_id: Optional[str] = None
    in_reply_to: Optional["BrainResponseInReplyTo"] = None
    utterance_id: Optional[str] = None
    model: Optional[str] = None
    backend: Optional[Literal["gpu", "cpu"]] = None
    latency_ms: Optional[float] = None
    TOPIC: ClassVar[str] = "brain.response"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['backend', 'conversation_id', 'in_reply_to', 'latency_ms', 'model', 'utterance_id'])


@dataclasses.dataclass
class CompatInstall:
    event: Literal["fingerprinted", "screened", "prefix_created", "installed", "failed", "blocked"]
    app: str
    sha256: str
    path: Optional[str] = None
    installer: Optional[Literal["nsis", "inno", "msi", "unknown"]] = None
    arch: Optional[Literal["x86", "x64", "arm64", "unknown"]] = None
    recipe: Optional[str] = None
    error: Optional[str] = None
    TOPIC: ClassVar[str] = "compat.install"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['arch', 'error', 'installer', 'path', 'recipe'])


@dataclasses.dataclass
class ContextSystem:
    net_online: bool
    load1: float
    mem_used_pct: float
    audio_volume: float
    audio_muted: bool
    battery_pct: Optional[float] = None
    gpu_vram_free_mb: Optional[float] = None
    TOPIC: ClassVar[str] = "context.system"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['battery_pct', 'gpu_vram_free_mb'])


@dataclasses.dataclass
class ContextWindow:
    kind: Literal["focus_changed", "opened", "closed", "title_changed"]
    window_id: int
    app_id: str
    title: Optional[str]
    workspace: Optional[str] = None
    monitor: Optional[str] = None
    focused: Optional[bool] = None
    redacted: Optional[bool] = None
    TOPIC: ClassVar[str] = "context.window"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['focused', 'monitor', 'redacted', 'workspace'])


@dataclasses.dataclass
class DialogListen:
    listen_id: str
    window_s: float
    reason: Literal["confirm", "onboarding", "followup"]
    TOPIC: ClassVar[str] = "dialog.listen"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset([])


@dataclasses.dataclass
class Envelope:
    topic: str
    ts: float
    seq: int
    src: str
    conf: float
    v: int
    body: Dict[str, Any]
    _optional: ClassVar[FrozenSet[str]] = frozenset([])


@dataclasses.dataclass
class GuardVerdict:
    sha256: str
    verdict: Literal["clean", "suspicious", "blocked"]
    reasons: List[str]
    scanned_by: Optional[List[str]] = None
    path: Optional[str] = None
    TOPIC: ClassVar[str] = "guard.verdict"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['path', 'scanned_by'])


@dataclasses.dataclass
class IntentAction:
    request_id: str
    tool: str
    args: Dict[str, Any]
    capability: Literal["observe", "benign", "destructive", "privileged"]
    needs_confirmation: Optional[bool] = None
    utterance_id: Optional[str] = None
    conversation_id: Optional[str] = None
    TOPIC: ClassVar[str] = "intent.action"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['conversation_id', 'needs_confirmation', 'utterance_id'])


@dataclasses.dataclass
class SpeechSay:
    text: str
    say_id: str
    in_reply_to_utterance: Optional[str]
    priority: Optional[Literal["low", "normal", "urgent"]] = None
    interruptible: Optional[bool] = None
    voice: Optional[str] = None
    TOPIC: ClassVar[str] = "speech.say"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['interruptible', 'priority', 'voice'])


@dataclasses.dataclass
class SpeechState:
    state: Literal["idle", "speaking", "interrupted"]
    say_id: Optional[str] = None
    reason: Optional[Literal["completed", "wake", "preempted", "error"]] = None
    TOPIC: ClassVar[str] = "speech.state"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['reason', 'say_id'])


@dataclasses.dataclass
class SysHealth:
    service: str
    state: Literal["starting", "ok", "degraded", "error", "stopping"]
    uptime_s: float
    period_s: float
    drops: Optional[Dict[str, int]] = None
    metrics: Optional[Dict[str, float]] = None
    notes: Optional[str] = None
    TOPIC: ClassVar[str] = "sys.health"
    V: ClassVar[int] = 1
    _optional: ClassVar[FrozenSet[str]] = frozenset(['drops', 'metrics', 'notes'])


def to_body(obj: Any) -> Dict[str, Any]:
    """Dataclass -> wire dict. Optional-and-absent fields are omitted
    (closed schemas reject null for them); required-nullable stay null."""
    out: Dict[str, Any] = {}
    for f in dataclasses.fields(obj):
        v = getattr(obj, f.name)
        if v is None and f.name in type(obj)._optional:
            continue
        if dataclasses.is_dataclass(v):
            v = to_body(v)
        elif isinstance(v, list):
            v = [to_body(x) if dataclasses.is_dataclass(x) else x for x in v]
        out[f.name] = v
    return out


def from_body(cls: type, body: Dict[str, Any]) -> Any:
    """Wire dict -> dataclass, recursing into nested dataclass fields."""
    hints = typing.get_type_hints(cls)
    kwargs: Dict[str, Any] = {}
    for f in dataclasses.fields(cls):
        if f.name not in body:
            continue
        v = body[f.name]
        t = hints[f.name]
        if typing.get_origin(t) is typing.Union:  # Optional[X]
            args = [a for a in typing.get_args(t) if a is not type(None)]
            t = args[0] if args else t
        if dataclasses.is_dataclass(t) and isinstance(v, dict):
            v = from_body(t, v)
        elif typing.get_origin(t) is list:
            (item,) = typing.get_args(t)
            if dataclasses.is_dataclass(item):
                v = [from_body(item, x) for x in v]
        kwargs[f.name] = v
    return cls(**kwargs)
