#!/usr/bin/env python3
"""Generate the HUD's Theme singleton from personality/theme.toml.

Theme tokens are identity (CLAUDE.md invariant 9), so they live in
`personality/` beside the voice and the system prompt — not scattered
through QML as hex codes nobody can diff. This generator turns that one
file into:

  shell/jv-hud/Theme.qml   a `pragma Singleton` QtObject of readonly tokens
  shell/jv-hud/qmldir      the registration that makes `import "."` work

Both outputs are checked in (so qmllint and the editor see them) and both
are verified with `--check`, which runs in the jv-hud build: a Theme.qml
that has drifted from theme.toml cannot reach a `nixos-rebuild build`.

Usage:
  python tools/gen_theme_qml.py            # write both files
  python tools/gen_theme_qml.py --check    # exit 1 if on-disk files differ
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # 3.10
    import tomli as tomllib  # type: ignore[no-redef]

ROOT = Path(__file__).resolve().parent.parent
THEME_TOML = ROOT / "personality" / "theme.toml"
OUT_DIR = ROOT / "shell" / "jv-hud"

HEADER = "GENERATED by tools/gen_theme_qml.py from personality/theme.toml — DO NOT EDIT."

# Sections, in the order they must appear. A token file that grows a section
# is a deliberate change to the generator too, not a typo that vanishes.
SECTIONS = ("palette", "type", "motion", "geometry")

# The tokens the HUD is allowed to assume exist. Adding a token is free;
# removing one of these breaks a consumer, so it fails here first.
REQUIRED = {
    "palette": ("ground", "text", "ember"),
    "type": ("family_mono", "label_px"),
    "motion": ("ease_ms",),
    "geometry": ("inset_px",),
}

# The qmldir is generated here too, because Theme.qml's registration has to
# live in it — so every OTHER singleton in shell/jv-hud has to be listed
# here as well, or a hand-written one silently stops resolving. Adding a
# singleton to the HUD means adding a line here; a test checks the two
# directories agree.
SINGLETONS = (
    ("Theme", "Theme.qml"),  # generated by this script
    ("Bus", "Bus.qml"),      # hand-written: the read-only bus bridge
)

# shell/jv-hud/core — the Quickshell-free half of the HUD. Importing a
# directory resolves every type its qmldir lists, so one file that needs the
# quickshell binary makes the WHOLE directory unimportable to any other QML
# engine. Logic that deserves a headless test therefore lives down here, with
# nothing but QtQuick above it, and the Quickshell singletons next door wrap
# it. A directory that ships a qmldir exposes only what the file lists, so an
# unregistered component is "not a type" — to the engine, to qmllint and to
# the tests alike. Add the line, or it does not exist.
CORE = (
    ("BusModel", "BusModel.qml"),  # the bus state machine, minus Quickshell
)

HEX = re.compile(r"^#[0-9A-F]{6}$")
SNAKE = re.compile(r"^[a-z][a-z0-9_]*$")


class ThemeError(Exception):
    """theme.toml says something that must never reach a screen."""


def load_tokens(text: str) -> dict[str, dict[str, object]]:
    """Parse and validate theme.toml, returning {section: {key: value}}."""
    try:
        data = tomllib.loads(text)
    except tomllib.TOMLDecodeError as e:  # pragma: no cover - message passthrough
        raise ThemeError(f"theme.toml is not valid TOML: {e}") from e

    for name in data:
        if name not in SECTIONS:
            raise ThemeError(f"unknown section [{name}] (expected one of {list(SECTIONS)})")
    for name in SECTIONS:
        if name not in data:
            raise ThemeError(f"missing section [{name}]")

    tokens: dict[str, dict[str, object]] = {}
    for name in SECTIONS:
        section = data[name]
        if not isinstance(section, dict) or not section:
            raise ThemeError(f"[{name}] must be a non-empty table")
        for key, value in section.items():
            where = f"{name}.{key}"
            if not SNAKE.match(key):
                raise ThemeError(f"{where}: keys are snake_case (got {key!r})")
            if isinstance(value, dict):
                raise ThemeError(f"{where}: nested tables are not tokens")
            if isinstance(value, list):
                raise ThemeError(f"{where}: lists are not tokens")
            if name == "palette" and not (isinstance(value, str) and HEX.match(value)):
                # One colour, one spelling: uppercase #RRGGBB or nothing.
                raise ThemeError(f"{where}: palette entries must be '#RRGGBB' uppercase (got {value!r})")
        for key in REQUIRED[name]:
            if key not in section:
                raise ThemeError(f"[{name}] is missing required token '{key}'")
        tokens[name] = dict(section)
    return tokens


def camel(key: str) -> str:
    head, *rest = key.split("_")
    return head + "".join(p.capitalize() for p in rest)


def qml_property(section: str, key: str, value: object) -> str:
    name = camel(key)
    if section == "palette":
        return f'  readonly property color {name}: "{value}"'
    if isinstance(value, bool):
        return f"  readonly property bool {name}: {'true' if value else 'false'}"
    if isinstance(value, int):
        return f"  readonly property int {name}: {value}"
    if isinstance(value, float):
        return f"  readonly property real {name}: {value!r}"
    return f'  readonly property string {name}: "{value}"'


SECTION_NOTES = {
    "palette": "Colour. Ember means Jarvis is doing something — spend it sparingly (§06).",
    "type": "Type. Sizes are px at 1x; tracking is em, so multiply by the size.",
    "motion": "Motion. Every duration is a signal settling, never decoration.",
    "geometry": "Geometry. The rhythm of a docked plate.",
}


def render_theme_qml(tokens: dict[str, dict[str, object]]) -> str:
    lines = [
        f"// {HEADER}",
        "//",
        "// The §06 design tokens, as the one thing every HUD element reads. If you",
        "// are about to type a hex code into a QML file: don't — put it in",
        "// personality/theme.toml and regenerate. The look is versioned with the",
        "// voice and the wake word (invariant 9), and it is diffable in one place.",
        "pragma Singleton",
        "import QtQuick",
        "",
        "QtObject {",
    ]
    for i, section in enumerate(SECTIONS):
        if i:
            lines.append("")
        lines.append(f"  // {SECTION_NOTES[section]}")
        for key, value in tokens[section].items():
            lines.append(qml_property(section, key, value))
    lines += ["}", ""]
    return "\n".join(lines)


def render_qmldir() -> str:
    return "\n".join(
        [
            f"# {HEADER}",
            "#",
            "# Quickshell synthesizes a qmldir per directory; shipping our own turns",
            "# that off for this one, which is what makes the singleton resolvable to",
            "# qmllint as well as to the engine. No `module` line: the HUD is imported",
            "# by directory (`import \".\"`), and claiming a module name Quickshell did",
            "# not assign only invites a collision. New singletons go in",
            "# SINGLETONS in tools/gen_theme_qml.py, which is what writes this.",
        ]
        + [f"singleton {name} 1.0 {file}" for name, file in SINGLETONS]
        + [""]
    )


def render_core_qmldir() -> str:
    return "\n".join(
        [
            f"# {HEADER}",
            "#",
            "# shell/jv-hud/core holds the HUD logic that imports nothing but",
            "# QtQuick, so `qmltestrunner` can load it without the quickshell",
            "# binary (which links its QML plugin into itself). Keep it that way:",
            "# one Quickshell import here would take the headless tests with it.",
            "# New components go in CORE in tools/gen_theme_qml.py.",
        ]
        + [f"{name} 1.0 {file}" for name, file in CORE]
        + [""]
    )


def outputs(theme_toml: Path) -> dict[str, str]:
    tokens = load_tokens(theme_toml.read_text(encoding="utf-8"))
    return {
        "Theme.qml": render_theme_qml(tokens),
        "qmldir": render_qmldir(),
        "core/qmldir": render_core_qmldir(),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if the on-disk files differ")
    ap.add_argument("--theme", type=Path, default=THEME_TOML, help="path to theme.toml")
    ap.add_argument("--out-dir", type=Path, default=OUT_DIR, help="directory holding the generated files")
    args = ap.parse_args(argv)

    try:
        generated = outputs(args.theme)
    except ThemeError as e:
        print(f"{args.theme}: {e}", file=sys.stderr)
        return 2

    stale = []
    for name, text in generated.items():
        path = args.out_dir / name
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if args.check:
            stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path}")
    if stale:
        print(
            "stale generated files: "
            + ", ".join(str(p) for p in stale)
            + "\nrun: python tools/gen_theme_qml.py",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
