#!/usr/bin/env python3
"""Compile the recorded perception sessions into the HUD tests' Sessions.qml.

PLAN B9. `harness/fixtures/sessions/*.jsonl` is what jv-ears really published
while listening to each fixture WAV — real openWakeWord, real Silero VAD, real
faster-whisper (B3). The HUD's headless QML tests used to hand-type the bridge
lines they asserted on, so the input and the expectation had the same author.
These recordings are the cure, but a QML engine cannot read a file out of the
repository, so they are compiled into one generated object:

  shell/jv-hud/tests/Sessions.qml   every recording, as the exact lines on disk

Committed like the generated Theme singleton (invariant 9), and verified the
same way: `--check` runs in the jv-hud build, so a re-recorded session and a
stale Sessions.qml cannot coexist in a build that passes.

This generator deliberately knows NOTHING about schemas. `harness/session.py`
is the format's only reader and `harness/tests/test_sessions.py` is what holds
these recordings to the generated bindings; a second validator here would be a
second truth to keep, and the wrong one would be believed by whoever read it
last. All this does is move bytes, verbatim, into a place QML can reach — which
is also why it imports nothing but the standard library: it runs under the
plain `python3` of the jv-hud build and under CI's bare checkout, where
`jarvis_bus` does not exist.

Usage:
  python tools/gen_sessions_qml.py           # write shell/jv-hud/tests/Sessions.qml
  python tools/gen_sessions_qml.py --check   # exit 1 if the committed file differs
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import sys
from pathlib import Path
from typing import List

ROOT = Path(__file__).resolve().parent.parent
SESSIONS_DIR = ROOT / "harness" / "fixtures" / "sessions"
OUT_DIR = ROOT / "shell" / "jv-hud" / "tests"
OUT_NAME = "Sessions.qml"

HEADER_NOTE = (
    "GENERATED by tools/gen_sessions_qml.py from harness/fixtures/sessions/*.jsonl "
    "— DO NOT EDIT."
)


class SessionsError(Exception):
    """A recording we refuse to compile into a test."""


@dataclasses.dataclass(frozen=True)
class Session:
    """One recording: its header line and its frame lines, byte for byte."""

    name: str
    header: str
    frames: List[str]


def _one_object(line: str, where: str) -> None:
    """Every line must be a JSON object and must be ASCII.

    Not a schema check — a legibility check. A line QML's `JSON.parse` would
    choke on has to fail here, while a human is looking at the generator,
    rather than inside a test that then asserts on nothing.
    """
    if not line.isascii():
        raise SessionsError(f"{where}: line is not ASCII (the recorders write ensure_ascii)")
    try:
        value = json.loads(line)
    except ValueError as e:
        raise SessionsError(f"{where}: not JSON ({e})") from e
    if not isinstance(value, dict):
        raise SessionsError(f"{where}: expected a JSON object, got {type(value).__name__}")


def load_session(path: Path) -> Session:
    """Read one `*.jsonl` recording: line 1 is the header, the rest are frames.

    That one sentence is the whole of this module's knowledge of the format
    (schemas/README.md, "Harness session header"). Everything else about a
    session — which fields an envelope has, what a topic means, whether the
    ordering is legal — belongs to harness/session.py and its tests.
    """
    lines = [l for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]
    if not lines:
        raise SessionsError(f"{path.name}: empty file, no session header")
    _one_object(lines[0], f"{path.name}:1")
    frames = lines[1:]
    if not frames:
        raise SessionsError(f"{path.name}: no frames — a recording nothing can replay")
    for n, line in enumerate(frames, start=2):
        _one_object(line, f"{path.name}:{n}")
    return Session(name=path.stem, header=lines[0], frames=frames)


def load_sessions(directory: Path) -> List[Session]:
    """Every recording in `directory`, sorted by name so the output is stable."""
    paths = sorted(directory.glob("*.jsonl"))
    if not paths:
        raise SessionsError(
            f"{directory}: no recordings (*.jsonl) — refusing to generate an "
            "empty fixture set that would make every test built on it vacuous"
        )
    return [load_session(p) for p in paths]


def _qml_string(line: str) -> str:
    # A JSON string literal is also a valid QML/JS one, and `json.dumps` of an
    # ASCII string escapes exactly the characters that need it.
    return json.dumps(line)


def render_sessions_qml(sessions: List[Session]) -> str:
    """The generated QML object. One `var` map, keyed by recording name."""
    out: List[str] = []
    w = out.append
    w(f"// {HEADER_NOTE}")
    w("//")
    w("// Every recorded perception session in harness/fixtures/sessions, as the")
    w("// exact JSONL lines committed there: `header` is the session header and")
    w("// `frames` are the envelopes jv-ears published, in order, unmodified.")
    w("//")
    w("// The HUD's tests replay these through core/BusModel to assert what the")
    w("// elements do with perception's REAL output instead of with frames typed")
    w("// by whoever wrote the expectation (PLAN B9). tst_sessionreplay.qml is")
    w("// the reader; harness/fixtures/sessions/README.md is the recording.")
    w("import QtQuick")
    w("")
    w("QtObject {")
    w("  // Every recording here, sorted. A test asserts this list is complete,")
    w("  // so a fixture that silently stops being compiled in is a failure and")
    w("  // not a suite that quietly got smaller.")
    names = ", ".join(_qml_string(s.name) for s in sessions)
    w(f"  readonly property var names: [{names}]")
    w("")
    w("  // name -> { header: string, frames: [string] }")
    w("  readonly property var byName: ({")
    for i, session in enumerate(sessions):
        tail = "" if i == len(sessions) - 1 else ","
        w(f"    {_qml_string(session.name)}: {{")
        w(f"      \"header\": {_qml_string(session.header)},")
        w("      \"frames\": [")
        for j, frame in enumerate(session.frames):
            comma = "" if j == len(session.frames) - 1 else ","
            w(f"        {_qml_string(frame)}{comma}")
        w("      ]")
        w(f"    }}{tail}")
    w("  })")
    w("}")
    return "\n".join(out) + "\n"


def main(argv: List[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--sessions", type=Path, default=SESSIONS_DIR, help="recordings directory")
    ap.add_argument("--out-dir", type=Path, default=OUT_DIR, help="where Sessions.qml goes")
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the file on disk is not what this would write",
    )
    args = ap.parse_args(argv)

    try:
        qml = render_sessions_qml(load_sessions(args.sessions))
    except SessionsError as e:
        print(f"gen_sessions_qml: {e}", file=sys.stderr)
        return 1

    target = args.out_dir / OUT_NAME
    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if current != qml:
            why = "missing" if current is None else "does not match the recordings"
            print(
                f"gen_sessions_qml: {target} {why}.\n"
                f"  Re-record and regenerate together: python tools/gen_sessions_qml.py",
                file=sys.stderr,
            )
            return 1
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(qml, encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
