#!/usr/bin/env python3
"""Generate a QML shell's Theme singleton from personality/theme.toml.

Theme tokens are identity (CLAUDE.md invariant 9), so they live in
`personality/` beside the voice and the system prompt — not scattered
through QML as hex codes nobody can diff. This generator turns that one
file into, for each shell in `SHELLS`:

  shell/<shell>/Theme.qml   a `pragma Singleton` QtObject of readonly tokens
  shell/<shell>/Ease.qml    the one gated Behavior every moving value uses
  shell/<shell>/Motion.qml  the singleton that says whether it may move at all
  shell/<shell>/core/MotionPolicy.qml  the decision behind it, in pure QtQuick
  shell/<shell>/qmldir      the registration that makes `import "."` work
  shell/<shell>/core/qmldir the same for the Quickshell-free half

There are three shells — `jv-hud`, the corner overlay, `jv-bar`, the top
bar, and `jv-notify`, the notification corner — and they get the SAME
Theme.qml, byte for byte. Not a shared import: each shell is copied into the
store on its own and `import "."` resolves inside one directory, so the file
has to exist in all of them. Generating them from one renderer is what keeps
"the HUD's corner, the bar's strip and a toast are one identity" a fact
rather than a hope.

The motion trio is here for the same reason and it matters more (PLAN D18):
`Ease` + `Motion` + `core/MotionPolicy` is the one place §06's stillness rule
is decidable — declared preference, session override, battery, fullscreen —
and a hand-copied second version of a DECISION is a second thing to drift.
Before this, only jv-hud had it: the bar could not move at all and the
notifier gated its one fade on the raw preference, honouring the versioned
token and nothing else. Now every shell gets the same three files, and the
byte-for-byte check below is what says all three still obey one switch.

Every output is checked in (so qmllint and the editor see them) and every
one is verified with `--check`, which runs in each shell's own build: a
Theme.qml that has drifted from theme.toml cannot reach a `nixos-rebuild
build`.

Usage:
  python tools/gen_theme_qml.py                    # write every shell's files
  python tools/gen_theme_qml.py --check            # exit 1 if any differ
  python tools/gen_theme_qml.py --shell jv-bar ... # one shell only

It also writes the files that are not any shell's: one
`<harness>/stub/Motion.qml` per entry in `STANDINS`, the stand-in a render
harness stages over its shell's Motion because the shots run under an engine
that cannot resolve Quickshell. Each is rendered from the same body as the real
one with three lines swapped (PLAN D29), so what a sheet photographs animates
for the reason the running shell would. There are three, one per shell: the
HUD's contact sheet (`ops/ralph/hudshots.sh`), the notification corner's
(`notifyshots.sh`, PLAN D20) and the top bar's (`barshots.sh`, PLAN D13).
"""

from __future__ import annotations

import argparse
import dataclasses
import re
import sys
from pathlib import Path
from typing import Iterable

try:
    import tomllib
except ModuleNotFoundError:  # 3.10
    import tomli as tomllib  # type: ignore[no-redef]

ROOT = Path(__file__).resolve().parent.parent
THEME_TOML = ROOT / "personality" / "theme.toml"
SHELL_DIR = ROOT / "shell"

HEADER = "GENERATED by tools/gen_theme_qml.py from personality/theme.toml — DO NOT EDIT."

# Sections, in the order they must appear. A token file that grows a section
# is a deliberate change to the generator too, not a typo that vanishes.
SECTIONS = ("palette", "type", "motion", "geometry")

# The tokens the HUD is allowed to assume exist. Adding a token is free;
# removing one of these breaks a consumer, so it fails here first.
REQUIRED = {
    "palette": ("ground", "text", "ember"),
    "type": ("family_mono", "label_px"),
    "motion": ("reduced_motion", "ease_ms"),
    "geometry": ("inset_px", "hud_corner_px"),
}

# What this script writes into EVERY shell, and therefore registers into
# every shell's qmldir without being named in any of the tables below: the
# tokens, and the motion trio that decides whether a value may move at all
# (PLAN D18). A fourth shell gets all four files by existing, which is the
# point — the one way a shell could end up with a Motion of its own is by
# someone copying one, and there is now nothing to copy.
GENERATED_SINGLETONS = (
    ("Theme", "Theme.qml"),    # the §06 tokens, from personality/theme.toml
    ("Motion", "Motion.qml"),  # may this shell move? (§06), bound to its sources
)

GENERATED_COMPONENTS = (
    ("Ease", "Ease.qml"),  # the one gated Behavior every moving value uses
)

GENERATED_CORE = (
    ("MotionPolicy", "MotionPolicy.qml"),  # the decision, in pure QtQuick (§06)
)

# The qmldir is generated here too, because Theme.qml's registration has to
# live in it — so every OTHER singleton in shell/jv-hud has to be listed
# here as well, or a hand-written one silently stops resolving. Adding a
# singleton to the HUD means adding a line here; a test checks the two
# directories agree.
SINGLETONS = (
    ("Bus", "Bus.qml"),  # hand-written: the read-only bus bridge
)

# Ordinary (non-singleton) types in shell/jv-hud. Our own qmldir replaces the
# one Quickshell would synthesize, and a qmldir exposes ONLY what it lists —
# so an unregistered component here is not a type at all, to the engine and
# to qmllint alike. shell.qml is the entry point, loaded by path, and is
# deliberately not listed.
COMPONENTS = (
    ("StatePlate", "StatePlate.qml"),  # what Jarvis is doing, on screen (A3)
    ("MicPlate", "MicPlate.qml"),  # the live-microphone indicator (A4)
    ("HealthPlate", "HealthPlate.qml"),  # what is wrong, when anything is (A6)
    ("ConfirmPlate", "ConfirmPlate.qml"),  # the question awaiting a yes/no (A20)
    ("LinkPlate", "LinkPlate.qml"),  # the HUD saying it cannot see the bus (A23)
    ("HeardPlate", "HeardPlate.qml"),  # the words Jarvis took down (A26)
    ("ActionPlate", "ActionPlate.qml"),  # the action that did not work (A37)
    ("OutputPlate", "OutputPlate.qml"),  # speaking into a silent output (A40)
    ("GuardPlate", "GuardPlate.qml"),  # the binary this machine refused (A51)
    ("InstallPlate", "InstallPlate.qml"),  # the app that did not install (A52)
    ("ReplyPlate", "ReplyPlate.qml"),  # the answer that was cut off (A71)
)

# shell/jv-hud/core — the Quickshell-free half of the HUD. Importing a
# directory resolves every type its qmldir lists, so one file that needs the
# quickshell binary makes the WHOLE directory unimportable to any other QML
# engine. Logic that deserves a headless test therefore lives down here, with
# nothing but QtQuick above it, and the Quickshell singletons next door wrap
# it. A directory that ships a qmldir exposes only what the file lists, so an
# unregistered component is "not a type" — to the engine, to qmllint and to
# the tests alike. Add the line, or it does not exist.
CORE = (
    ("BusModel", "BusModel.qml"),  # the bus state machine, minus Quickshell
    ("SpeechState", "SpeechState.qml"),  # what is Jarvis doing? (A3)
    ("MicState", "MicState.qml"),  # is the microphone open? (A4)
    ("HealthState", "HealthState.qml"),  # is anything wrong with Jarvis? (A6)
    ("ConfirmState", "ConfirmState.qml"),  # is Jarvis waiting on a yes/no? (A20)
    ("LinkState", "LinkState.qml"),  # can the HUD see the bus at all? (A23)
    ("HeardState", "HeardState.qml"),  # what did Jarvis hear you say? (A26)
    ("ActionState", "ActionState.qml"),  # did what Jarvis tried to do fail? (A37)
    ("OutputState", "OutputState.qml"),  # can you hear what Jarvis is saying? (A40)
    ("VramState", "VramState.qml"),  # how much of the card is left? (B40)
    ("DropState", "DropState.qml"),  # did the bus throw frames away? (A75)
    ("GuardState", "GuardState.qml"),  # was a binary refused, and which? (A51)
    ("InstallState", "InstallState.qml"),  # did an install fail, and which? (A52)
    ("ReplyState", "ReplyState.qml"),  # was the last reply cut off? (A71)
    ("PlateStack", "PlateStack.qml"),  # is ANYTHING on screen? (A15)
    ("EarsBudgets", "EarsBudgets.qml"),  # how is jv-ears tuned? (A14)
)

# shell/jv-bar — the top bar (PLAN D1). Its own three registries, not an
# extension of the HUD's: the two shells are separate Quickshell processes,
# each copied into the store on its own, and `import "."` resolves inside ONE
# directory. A single table would register the HUD's plates into the bar's
# qmldir, where every one of them is a file that does not exist.
BAR_SINGLETONS = (
    ("Niri", "Niri.qml"),  # hand-written: the read-only niri event stream
)

BAR_COMPONENTS = (
    ("Workspaces", "Workspaces.qml"),  # niri's workspaces for one output (D1)
    ("Clock", "Clock.qml"),  # the time, in the middle of the strip (D1)
)

# shell/jv-bar/core — the bar's Quickshell-free half, for the same reason the
# HUD has one: `qmltestrunner` cannot load a directory that imports Quickshell.
BAR_CORE = (
    ("NiriModel", "NiriModel.qml"),  # what the compositor has said (D1)
    ("WallClock", "WallClock.qml"),  # a time, as the glyphs a bar shows (D1)
    ("RowFit", "RowFit.qml"),  # which labels fit, and what the rest collapse to (D32)
)


# shell/jv-notify — the notification corner (PLAN D2): this machine's
# org.freedesktop.Notifications daemon, drawn in §06. A third set of
# registries for the third Quickshell process, and the same reason as the
# bar's: one table would register a type into a directory where its file does
# not exist.
NOTIFY_SINGLETONS = (
    ("Notifications", "Notifications.qml"),  # hand-written: the D-Bus server (D2)
)

NOTIFY_COMPONENTS = (
    ("Toast", "Toast.qml"),  # one notification, as a plate (D2)
)

# shell/jv-notify/core — the notifier's Quickshell-free half. The whole
# lifecycle of what is on screen lives here (what is shown, in what order,
# for how long), which is what gives `notifytest.sh` something to run.
NOTIFY_CORE = (
    ("NotifyModel", "NotifyModel.qml"),  # what is on screen, and until when (D2)
)


@dataclasses.dataclass(frozen=True)
class Shell:
    """One QML shell that consumes the tokens, and what its qmldirs list.

    `name` is the directory under `shell/` and the package name. `owner` is
    how the core qmldir refers to the shell in prose, and `registry` is the
    prefix of the three tables above — both exist so the generated comment
    names the table a reader has to edit, which is the whole point of writing
    a comment into a generated file.

    The three tuples are the FULL registries — the shell's own hand-written
    types with everything this script generates already in front of them (see
    `_shell`), because "what the qmldir lists" and "what is in the directory"
    is one question and a reader of either should get one answer.
    """

    name: str
    owner: str
    registry: str
    singletons: tuple[tuple[str, str], ...]
    components: tuple[tuple[str, str], ...]
    core: tuple[tuple[str, str], ...]


def _shell(
    name: str,
    owner: str,
    registry: str,
    singletons: tuple[tuple[str, str], ...],
    components: tuple[tuple[str, str], ...],
    core: tuple[tuple[str, str], ...],
) -> Shell:
    """One shell: its hand-written tables, behind the generated ones.

    The generated types come FIRST in every registry so the qmldir opens with
    the four files this script owns — a reader who wants to know why a line is
    there gets "because the generator writes it into every shell" before the
    shell's own vocabulary starts.
    """
    return Shell(
        name,
        owner,
        registry,
        GENERATED_SINGLETONS + singletons,
        GENERATED_COMPONENTS + components,
        GENERATED_CORE + core,
    )


SHELLS = {
    s.name: s
    for s in (
        _shell("jv-hud", "the HUD's", "", SINGLETONS, COMPONENTS, CORE),
        _shell("jv-bar", "the bar's", "BAR_", BAR_SINGLETONS, BAR_COMPONENTS, BAR_CORE),
        _shell(
            "jv-notify",
            "the notifier's",
            "NOTIFY_",
            NOTIFY_SINGLETONS,
            NOTIFY_COMPONENTS,
            NOTIFY_CORE,
        ),
    )
}

HEX = re.compile(r"^#[0-9A-F]{6}$")
SNAKE = re.compile(r"^[a-z][a-z0-9_]*$")


class ThemeError(Exception):
    """theme.toml says something that must never reach a screen."""


def load_tokens(text: str) -> dict[str, dict[str, object]]:
    """Parse and validate theme.toml, returning {section: {key: value}}."""
    try:
        data = tomllib.loads(text)
    except tomllib.TOMLDecodeError as e:  # pragma: no cover - message passthrough
        raise ThemeError(f"theme.toml is not valid TOML: {e}") from e

    for name in data:
        if name not in SECTIONS:
            raise ThemeError(f"unknown section [{name}] (expected one of {list(SECTIONS)})")
    for name in SECTIONS:
        if name not in data:
            raise ThemeError(f"missing section [{name}]")

    tokens: dict[str, dict[str, object]] = {}
    for name in SECTIONS:
        section = data[name]
        if not isinstance(section, dict) or not section:
            raise ThemeError(f"[{name}] must be a non-empty table")
        for key, value in section.items():
            where = f"{name}.{key}"
            if not SNAKE.match(key):
                raise ThemeError(f"{where}: keys are snake_case (got {key!r})")
            if isinstance(value, dict):
                raise ThemeError(f"{where}: nested tables are not tokens")
            if isinstance(value, list):
                raise ThemeError(f"{where}: lists are not tokens")
            if name == "palette" and not (isinstance(value, str) and HEX.match(value)):
                # One colour, one spelling: uppercase #RRGGBB or nothing.
                raise ThemeError(f"{where}: palette entries must be '#RRGGBB' uppercase (got {value!r})")
        for key in REQUIRED[name]:
            if key not in section:
                raise ThemeError(f"[{name}] is missing required token '{key}'")
        tokens[name] = dict(section)
    return tokens


def camel(key: str) -> str:
    head, *rest = key.split("_")
    return head + "".join(p.capitalize() for p in rest)


def qml_property(section: str, key: str, value: object) -> str:
    name = camel(key)
    if section == "palette":
        return f'  readonly property color {name}: "{value}"'
    if isinstance(value, bool):
        return f"  readonly property bool {name}: {'true' if value else 'false'}"
    if isinstance(value, int):
        return f"  readonly property int {name}: {value}"
    if isinstance(value, float):
        return f"  readonly property real {name}: {value!r}"
    return f'  readonly property string {name}: "{value}"'


SECTION_NOTES = {
    "palette": "Colour. Ember means Jarvis is doing something — spend it sparingly (§06).",
    "type": "Type. Sizes are px at 1x; tracking is em, so multiply by the size.",
    "motion": "Motion. Every duration is a signal settling, never decoration.",
    "geometry": "Geometry. The rhythm of a docked plate.",
}


def render_theme_qml(tokens: dict[str, dict[str, object]]) -> str:
    lines = [
        f"// {HEADER}",
        "//",
        "// The §06 design tokens, as the one thing every element of every shell",
        "// reads — the HUD's corner and the bar's strip are the same identity. If you",
        "// are about to type a hex code into a QML file: don't — put it in",
        "// personality/theme.toml and regenerate. The look is versioned with the",
        "// voice and the wake word (invariant 9), and it is diffable in one place.",
        "pragma Singleton",
        "import QtQuick",
        "",
        "QtObject {",
    ]
    for i, section in enumerate(SECTIONS):
        if i:
            lines.append("")
        lines.append(f"  // {SECTION_NOTES[section]}")
        for key, value in tokens[section].items():
            lines.append(qml_property(section, key, value))
    lines += ["}", ""]
    return "\n".join(lines)


def render_qmldir(shell: Shell) -> str:
    return "\n".join(
        [
            f"# {HEADER}",
            "#",
            "# Quickshell synthesizes a qmldir per directory; shipping our own turns",
            "# that off for this one, which is what makes the singleton resolvable to",
            "# qmllint as well as to the engine. No `module` line: a shell is imported",
            "# by directory (`import \".\"`), and claiming a module name Quickshell did",
            "# not assign only invites a collision. The first lines are the files the",
            "# generator writes into EVERY shell (the tokens and the motion trio);",
            "# new hand-written singletons go in",
            f"# {shell.registry}SINGLETONS in tools/gen_theme_qml.py — and other types in",
            f"# {shell.registry}COMPONENTS — which is what writes this.",
        ]
        + [f"singleton {name} 1.0 {file}" for name, file in shell.singletons]
        + [f"{name} 1.0 {file}" for name, file in shell.components]
        + [""]
    )


def render_core_qmldir(shell: Shell) -> str:
    return "\n".join(
        [
            f"# {HEADER}",
            "#",
            f"# shell/{shell.name}/core holds {shell.owner} logic that imports nothing",
            "# but QtQuick, so `qmltestrunner` can load it without the quickshell",
            "# binary (which links its QML plugin into itself). Keep it that way:",
            "# one Quickshell import here would take the headless tests with it.",
            "# MotionPolicy is generated into every shell; the rest are this one's, and",
            f"# new ones go in {shell.registry}CORE in tools/gen_theme_qml.py.",
        ]
        + [f"{name} 1.0 {file}" for name, file in shell.core]
        + [""]
    )


# The environment variable that stills EVERY surface for one session. One
# machine, one switch: three shells draw one desktop, and a stillness that
# reached the HUD's corner while the bar and the toasts kept moving would be
# a preference half-obeyed, which is worse than one never offered.
MOTION_ENV = "JV_REDUCED_MOTION"

EASE_BODY = """//
// Ease — this shell's one way to make a value move (PLAN A7).
//
// §06: "ease toward target over ~200ms (never raw pose)". A surface that
// assigns a sensor value straight to a visual property twitches; a surface
// whose every element hand-rolls its own Behavior eventually has one that
// forgot the reduced-motion switch. So there is one component, used as a
// property interceptor on whatever is allowed to move:
//
//     Text { color: live ? Theme.text2 : Theme.text3
//            Ease on color {} }
//
//     Rectangle { opacity: shown ? 1 : 0
//                 Ease on opacity { base: Theme.fadeInMs } }
//
// It is a PropertyAnimation rather than a NumberAnimation on purpose: the
// same component then eases colours, which is most of what these surfaces
// settle.
//
// The gate cannot be worked around from the outside — `base` is a token in
// milliseconds, but the duration that reaches the animation is always
// Motion.ms(base), so a caller can choose how long a move takes and never
// whether it happens. With motion suppressed the Behavior is disabled
// outright, so the value is assigned directly and no frame is rendered.
import QtQuick

Behavior {
  id: root

  // Which §06 duration this move takes, before gating. Default: the ease.
  property real base: Theme.easeMs

  enabled: Motion.animate

  animation: PropertyAnimation {
    duration: Motion.ms(root.base)
    // Decelerate into the target: the value arrives without overshoot and
    // without a bounce, which reads as a signal settling rather than as an
    // effect playing.
    easing.type: Easing.OutCubic
  }
}
"""

MOTION_HEAD = """//
// Motion — this shell's permission to move, bound to its real sources (A7).
//
// The decision itself is next door in core/MotionPolicy.qml, where it is
// pure QtQuick and therefore tested. This file is the wiring: it hands the
// policy the preference a human actually set, and republishes the §06
// duration tokens with the gate already applied, so an element writes
//
//     Behavior on opacity { enabled: Motion.animate
//                           NumberAnimation { duration: Motion.easeMs } }
//
// or, for the common case, just `Ease on opacity {}` — and "motion off"
// stops being a rule every element has to remember. The durations are 0
// while motion is suppressed, so even an animation that forgot to check
// `animate` still cannot move the screen.
//
// Nothing here is a sensor: this is a preference and a machine state, never
// something the room is doing. Elements gate their MOTION on it, never their
// CONTENT — a still surface must still tell the truth.
pragma Singleton

import QtQuick
@IMPORT@import "core"

@ROOT@ {
  id: root

  // May this shell animate at all? Gate `Behavior.enabled` and any standalone
  // animation's `running` on this: a disabled Behavior assigns straight
  // through, which costs zero frames rather than a zero-length animation.
  readonly property bool animate: policy.animate

  // Why motion is off ("" while it is on) — for a diagnostics readout, and
  // so "why did it go still?" has an answer that is not a guess.
  readonly property string suppressedBy: policy.suppressedBy

  // The §06 durations, already gated: one property per `*_ms` token in
  // personality/theme.toml, under the token's own name. Reach for
  // Motion.easeMs, not Theme.easeMs, whenever the number is going to end up
  // in an animation."""

MOTION_TAIL = """
  // Gate any other duration (a per-element one, a fraction of a token)
  // through here, so it obeys the same switch.
  function ms(base: real): real {
    return policy.ms(base);
  }

  readonly property MotionPolicy policy: MotionPolicy {
    // The standing preference, versioned in personality/theme.toml.
    declaredReduced: Theme.reducedMotion
@ENVOVERRIDE@
    // fullscreen/onBattery are left at false: no source publishes either
    // one yet (see core/MotionPolicy.qml). When one does, it binds here.
  }
}
"""

# Motion.qml is rendered once per shell from the body above, and once MORE per
# render harness, as the stand-in that harness stages over its shell's
# (PLAN D29, and D20 for the second one). A stand-in exists for one reason —
# the shots run under plain `qml`, and Quickshell links its QML plugin into its
# own binary, so `Quickshell.env` cannot resolve there — and the first one was a
# HAND COPY of this file until D29, which is precisely the failure this
# generator exists to prevent one level down. Rendering them here means exactly
# three things differ, all of them named below, and "a shot animates for the
# reason the running shell would" stops being a comment and becomes the same
# bytes.
@dataclasses.dataclass(frozen=True)
class MotionTarget:
    """What one rendering of Motion.qml does NOT share with the other.

    `preface` is prose in front of the shared doc comment (a reader of the
    stand-in needs to know it is one before anything else); `imports` is the
    line under `import QtQuick`; `root` is the root type; `env` is the
    `envOverride:` binding with the comment that explains it. Everything a
    Motion actually DOES — the gate, the republished durations, `ms()`, the
    policy it hands the declared preference to — is in MOTION_HEAD/TAIL and
    cannot differ between any two of them.
    """

    preface: str
    imports: str
    root: str
    env: str


SHELL_MOTION = MotionTarget(
    preface="",
    # Quickshell for `Quickshell.env`, and Singleton because a shell's
    # Motion is registered as one in the qmldir this script also writes.
    imports="import Quickshell\n",
    root="Singleton",
    # Single-quoted so the binding can end in the empty string it actually
    # ends in, without the quotes running into the closing delimiter.
    env='''    // …and a per-session override for a machine you are sitting at right
    // now: @ENV@=1 to stop motion, =0 to force it back on. The same
    // variable in every shell, because they draw one desktop between them.
    // Quickshell.env returns null when unset; the policy expects a string.
    envOverride: Quickshell.env("@ENV@") || ""''',
)

# The preface, with the one harness-specific sentence still derived rather than
# written twice: WHICH shell this stands in for and WHICH script stages it are
# the only facts a second stand-in changes, so they are the only holes in it.
STANDIN_PREFACE = """//
// THE RENDER HARNESS'S STAND-IN for shell/@SHELL@/Motion.qml, staged over
// it when that shell is photographed by @SCRIPT@.
// Generated from the same body as the real one, with the three lines that
// CANNOT be shared swapped: the Quickshell import, the root type, and where
// the session override comes from. Everything else below is the running
// shell's own file, so a shot animates — or does not — for the reason the
// running shell would."""

STANDIN_MOTION = MotionTarget(
    # Filled in per harness by `standin_motion` below; a bare rendering of this
    # target would say `shell/@SHELL@`, which is why nothing renders it.
    preface=STANDIN_PREFACE,
    # No Quickshell import at all: one of them anywhere in the staged tree
    # makes the whole directory unimportable to every engine but quickshell's
    # own, which is the entire reason this file exists. QtObject rather than
    # Quickshell's Singleton for the same reason; `pragma Singleton` above is
    # what the staged qmldir's `singleton Motion` line needs, and Theme.qml is
    # registered exactly this way.
    imports="",
    root="QtObject",
    env='''    // …and the session override, fixed at "" — the one line that cannot be
    // the real file's, and also the one that should not be: a shot taken
    // with a developer's @ENV@ in the environment
    // would be a picture of that shell rather than of the declared look.
    // The driver waits past the longest §06 duration before it grabs, so
    // what lands in the PNG is the settled frame either way.
    envOverride: ""''',
)


@dataclasses.dataclass(frozen=True)
class Standin:
    """One render harness's stand-in Motion: whose it replaces, and where.

    `shell` is the shell whose `Motion.qml` this is staged OVER, which is also
    the shell whose generator run emits it — a stand-in rewritten by a run that
    has nothing to do with it is a surprise in someone else's diff (PLAN D29).
    `dir` is where it is written (absolute, so a build sandbox running this
    script with `--out-dir` cannot be handed a path inside itself), and
    `script` is the harness that does the staging, named in the file's own
    preface so a reader can find the thing that uses it.
    """

    shell: str
    dir: Path
    script: str


# The three harnesses that photograph a shell — one per shell, now that the
# bar has one too (PLAN D13). Each stages its own stand-in
# because `import "."` resolves inside ONE directory and each harness assembles
# its own stage; the FILES are generated from one body, which is the whole
# point of D29 — and what made the second harness (D20) and the third (D13) a
# one-line table entry each rather than another hand copy.
STANDINS = (
    Standin("jv-hud", ROOT / "tools" / "hudshots" / "stub", "ops/ralph/hudshots.sh"),
    Standin("jv-notify", ROOT / "tools" / "notifyshots" / "stub", "ops/ralph/notifyshots.sh"),
    Standin("jv-bar", ROOT / "tools" / "barshots" / "stub", "ops/ralph/barshots.sh"),
)


def standin_motion(standin: Standin) -> MotionTarget:
    """`STANDIN_MOTION` with the harness's own two facts filled in."""
    return dataclasses.replace(
        STANDIN_MOTION,
        preface=STANDIN_PREFACE.replace("@SHELL@", standin.shell).replace(
            "@SCRIPT@", standin.script
        ),
    )


MOTION_POLICY_BODY = """//
// MotionPolicy — the single answer to "is this shell allowed to move?" (A7).
//
// §06 gives motion four rules, and three of them are about NOT moving:
//
//     ease toward target over ~200ms (never raw pose) · full stop when a
//     window is fullscreen · off on battery · off with prefers-reduced-motion
//
// If each element remembered those on its own, one element would eventually
// forget, and the forgetting would be invisible — a surface that still
// breathes after you asked it to stop. So the decision lives here, once, and
// every animation in the shell is gated on it through the `Motion` singleton
// next door (which is what binds these inputs to their real sources).
//
// This file is the half that is pure QtQuick, so the decision is testable
// headlessly: given a preference and a machine state, does it animate, and
// what does it say the reason was? `Motion.qml` is the wiring. It is the same
// file in every shell — generated, not copied — so the one suite that reads
// it (shell/jv-hud/tests/tst_motionpolicy.qml) is testing all of them.
//
// On the inputs: `declaredReduced` and `envOverride` have real sources today
// (personality/theme.toml and the environment). `onBattery` and `fullscreen`
// do NOT — nothing on the bus reports either one yet (context.system carries
// `battery_pct`, which says nothing about whether the machine is discharging,
// and context.window has no fullscreen field). They are inputs rather than
// TODOs so that wiring them later is one binding and not a redesign; until
// then they sit at false, which is the truth on ares — a desktop with no
// battery. Anything that starts feeding them must feed them a real signal.
import QtQuick

QtObject {
  id: root

  // The standing preference from personality/theme.toml (Theme.reducedMotion).
  property bool declaredReduced: false

  // A per-session override, as the environment spells it: "1" forces reduced
  // motion on, "0" forces it off, and anything else — including unset, which
  // arrives here as the empty string — defers to the declared preference.
  // Only those two exact strings count: a machine that reads "true" as true
  // and "yes" as false is a machine nobody can predict. It is parsed here,
  // rather than at the env lookup, because here it has tests.
  property string envOverride: ""

  // A window is fullscreen on the screen this element lives on. No source yet.
  property bool fullscreen: false
  // The machine is running on battery. No source yet (ares has none).
  property bool onBattery: false

  readonly property bool prefersReduced: root.envOverride === "1" ? true : root.envOverride === "0" ? false : root.declaredReduced

  // Why motion is off, or "" when it is on. A reason rather than a bare
  // bool because "the surface went still" is a question someone will ask, and
  // the honest answer is cheap to keep. Order is severity, not preference:
  // the user's own wish is named first even when the machine also has a say.
  readonly property string suppressedBy: root.prefersReduced ? "reduced-motion" : root.onBattery ? "battery" : root.fullscreen ? "fullscreen" : ""

  // The one thing elements read: gate `Behavior.enabled` (or an animation's
  // `running`) on it and stillness costs no frames at all, rather than
  // running an animation that happens to take zero time.
  readonly property bool animate: root.suppressedBy === ""

  // A duration token, gated: `base` while motion is allowed, 0 otherwise.
  // Anything that is not a positive number is 0 as well — a duration is a
  // length of time, and QML would otherwise happily animate for NaN
  // milliseconds. (`base` is declared `real`, so a numeric string arrives
  // here already converted; it is the values that survive conversion as
  // nonsense that this has to catch.)
  function ms(base: real): real {
    return root.animate && base > 0 ? base : 0;
  }
}
"""


def render_ease_qml() -> str:
    """shell/<shell>/Ease.qml — the one gated Behavior in a shell (PLAN D18)."""
    return f"// {HEADER}\n" + EASE_BODY


def render_motion_qml(
    tokens: dict[str, dict[str, object]], target: MotionTarget = SHELL_MOTION
) -> str:
    """Motion.qml — the policy, wired to what this machine says.

    Every `*_ms` token in [motion] is republished gated, so a new duration in
    theme.toml arrives in `Motion` without anyone remembering to add it — and
    an element that reaches for `Motion.<token>` cannot get an ungated number.
    That is also why a render harness's stand-in is rendered from here
    (`target=standin_motion(...)`): a duration that reached a shell and not the
    photograph of it would make the sheet a picture of a different shell.
    """
    head = MOTION_HEAD.replace("@IMPORT@", target.imports).replace("@ROOT@", target.root)
    lines = [f"// {HEADER}"] + target.preface.splitlines() + head.splitlines()
    for key, value in tokens["motion"].items():
        if not key.endswith("_ms"):
            continue
        # A duration is a number; `int` for the whole milliseconds §06 deals
        # in, `real` for anything else, because a truncated duration is a
        # silently different look.
        kind = "int" if isinstance(value, int) and not isinstance(value, bool) else "real"
        lines.append(f"  readonly property {kind} {camel(key)}: policy.ms(Theme.{camel(key)})")
    tail = MOTION_TAIL.replace("@ENVOVERRIDE@", target.env).replace("@ENV@", MOTION_ENV)
    lines += tail.splitlines()
    return "\n".join(lines) + "\n"


def render_motion_policy_qml() -> str:
    """shell/<shell>/core/MotionPolicy.qml — the decision, in pure QtQuick."""
    return f"// {HEADER}\n" + MOTION_POLICY_BODY


def outputs(theme_toml: Path, shell: Shell) -> dict[str, str]:
    tokens = load_tokens(theme_toml.read_text(encoding="utf-8"))
    return {
        "Theme.qml": render_theme_qml(tokens),
        "Ease.qml": render_ease_qml(),
        "Motion.qml": render_motion_qml(tokens),
        "core/MotionPolicy.qml": render_motion_policy_qml(),
        "qmldir": render_qmldir(shell),
        "core/qmldir": render_core_qmldir(shell),
    }


def stub_outputs(theme_toml: Path, standins: Iterable[Standin] = STANDINS) -> dict[Path, str]:
    """The render harnesses' staged files, by absolute path (PLAN D29, D20).

    Keyed by path rather than by name because these do not live under
    `shell/`: a harness is not a shell, it is the thing that photographs one,
    and it stages its copy over that shell's `Motion.qml` at render time.
    """
    tokens = load_tokens(theme_toml.read_text(encoding="utf-8"))
    return {
        s.dir / "Motion.qml": render_motion_qml(tokens, standin_motion(s)) for s in standins
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if the on-disk files differ")
    ap.add_argument("--theme", type=Path, default=THEME_TOML, help="path to theme.toml")
    ap.add_argument(
        "--shell",
        action="append",
        choices=sorted(SHELLS),
        help="the shell to generate for (repeatable; default: all of them)",
    )
    # Only meaningful with exactly one --shell: a build sandbox holds one
    # shell's tree and nothing else, which is the case that needs it. Without
    # it each shell is written to shell/<name> in this checkout.
    ap.add_argument("--out-dir", type=Path, default=None, help="where one shell's files go")
    args = ap.parse_args(argv)

    shells = [SHELLS[n] for n in (args.shell or sorted(SHELLS))]
    if args.out_dir is not None and len(shells) != 1:
        ap.error("--out-dir needs exactly one --shell")

    stale: list[Path] = []

    def emit(path: Path, text: str) -> None:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            return
        if args.check:
            stale.append(path)
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path}")

    for shell in shells:
        try:
            generated = outputs(args.theme, shell)
        except ThemeError as e:
            print(f"{args.theme}: {e}", file=sys.stderr)
            return 2

        out_dir = args.out_dir if args.out_dir is not None else SHELL_DIR / shell.name
        for name, text in generated.items():
            emit(out_dir / name, text)

    # A render harness's stand-in goes out with the shell it stands in for
    # (PLAN D29) — and only in this checkout: `--out-dir` is a build sandbox
    # holding ONE shell's tree, where tools/ does not exist at all.
    named = {s.name for s in shells}
    mine = [s for s in STANDINS if s.shell in named]
    if args.out_dir is None and mine:
        try:
            for path, text in stub_outputs(args.theme, mine).items():
                emit(path, text)
        except ThemeError as e:
            print(f"{args.theme}: {e}", file=sys.stderr)
            return 2
    if stale:
        print(
            "stale generated files: "
            + ", ".join(str(p) for p in stale)
            + "\nrun: python tools/gen_theme_qml.py",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
