#!/usr/bin/env python3
"""Generate Rust + Python typed bindings from schemas/*.json.

Outputs (checked into the repo; CI runs `--check` and fails on drift):
  services/jarvisd/src/schema.rs        Rust structs/enums + topic consts
  services/pylib/jarvis_bus/schema.py   Python dataclasses + topic consts

Deliberately supports only the subset of JSON Schema the frozen v1 set
uses. If a future schema needs more, extend this generator in the same
commit (invariant 2: schema changes are reviewed commits).

Usage:
  python tools/gen_bindings.py           # write both files
  python tools/gen_bindings.py --check   # exit 1 if on-disk files differ
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMAS = ROOT / "schemas"
RUST_OUT = ROOT / "services" / "jarvisd" / "src" / "schema.rs"
PY_OUT = ROOT / "services" / "pylib" / "jarvis_bus" / "schema.py"

HEADER = "GENERATED by tools/gen_bindings.py from schemas/*.json — DO NOT EDIT."


def pascal(s: str) -> str:
    return "".join(p.capitalize() for p in re.split(r"[._\-]", s) if p)


def const_name(topic: str) -> str:
    return topic.replace(".", "_").upper()


def load_schemas():
    """Return [(struct_name, topic_or_None, version, schema_dict)] sorted by file."""
    out = []
    for f in sorted(SCHEMAS.glob("*.json")):
        sch = json.loads(f.read_text(encoding="utf-8"))
        m = re.search(r"/v(\d+)$", sch["$id"])
        if not m:
            sys.exit(f"{f.name}: $id has no /vN suffix")
        version = int(m.group(1))
        stem = f.name[: -len(".json")]
        topic = None if stem == "envelope" else stem
        out.append((pascal(stem), topic, version, sch))
    return out


class Field:
    def __init__(self, name, prop, required, owner):
        self.name = name
        self.prop = prop
        self.required = required
        self.owner = owner  # struct name prefix for nested types
        t = prop.get("type")
        self.nullable = isinstance(t, list) and "null" in t
        if self.nullable:
            rest = [x for x in t if x != "null"]
            if rest != ["string"]:
                sys.exit(f"{owner}.{name}: only nullable string is supported")
            t = "string"
        self.kind, self.detail = self._classify(t)

    def _classify(self, t):
        p = self.prop
        if "enum" in p:
            return "enum", p["enum"]
        if t == "string":
            return "string", None
        if t == "number":
            return "number", None
        if t == "integer":
            return "integer", None
        if t == "boolean":
            return "boolean", None
        if t == "array":
            items = p.get("items", {})
            if items.get("type") == "object" and "properties" in items:
                return "array_struct", items
            if items.get("type") in ("string", "number", "integer", "boolean"):
                return "array_scalar", items["type"]
            sys.exit(f"{self.owner}.{self.name}: unsupported array items")
        if t == "object":
            ap = p.get("additionalProperties")
            if "properties" in p:
                return "struct", p
            if isinstance(ap, dict) and ap.get("type") in ("number", "integer"):
                return "map", ap["type"]
            return "any", None  # free-form (envelope.body)
        sys.exit(f"{self.owner}.{self.name}: unsupported type {t!r}")

    @property
    def nested_name(self):
        n = self.name[:-1] if self.kind == "array_struct" and self.name.endswith("s") else self.name
        return self.owner + pascal(n)


def collect_fields(struct_name, schema):
    req = schema.get("required", [])
    fields, nested = [], []
    seen_optional = False
    for name, prop in schema["properties"].items():
        fld = Field(name, prop, name in req, struct_name)
        if fld.required and seen_optional:
            sys.exit(f"{struct_name}.{name}: required fields must precede optional ones")
        seen_optional = seen_optional or not fld.required
        fields.append(fld)
        if fld.kind in ("struct", "array_struct"):
            sub = fld.prop if fld.kind == "struct" else fld.prop["items"]
            nested.append((fld.nested_name, sub))
    return fields, nested


# ---------------------------------------------------------------- Rust

def rust_type(fld: Field) -> str:
    base = {
        "string": "String",
        "number": "f64",
        "integer": "u64",
        "boolean": "bool",
        "any": "rmpv::Value",
    }.get(fld.kind)
    if fld.kind == "enum":
        base = fld.owner + pascal(fld.name)
    elif fld.kind == "map":
        base = f"BTreeMap<String, {'f64' if fld.detail == 'number' else 'u64'}>"
    elif fld.kind == "struct":
        base = fld.nested_name
    elif fld.kind == "array_struct":
        base = f"Vec<{fld.nested_name}>"
    elif fld.kind == "array_scalar":
        inner = {"string": "String", "number": "f64", "integer": "u64", "boolean": "bool"}
        base = f"Vec<{inner[fld.detail]}>"
    if fld.nullable or not fld.required:
        return f"Option<{base}>"
    return base


def rust_struct(name, schema, lines):
    fields, nested = collect_fields(name, schema)
    for sub_name, sub in nested:
        rust_struct(sub_name, sub, lines)
    for fld in fields:
        if fld.kind == "enum":
            lines.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]")
            lines.append('#[serde(rename_all = "snake_case")]')
            lines.append(f"pub enum {fld.owner}{pascal(fld.name)} {{")
            for v in fld.detail:
                lines.append(f"    {pascal(v)},")
            lines.append("}")
            lines.append("")
    lines.append("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]")
    lines.append("#[serde(deny_unknown_fields)]")
    lines.append(f"pub struct {name} {{")
    for fld in fields:
        if not fld.required:
            lines.append('    #[serde(default, skip_serializing_if = "Option::is_none")]')
        # required + nullable: plain Option — missing errors, null = None
        lines.append(f"    pub {fld.name}: {rust_type(fld)},")
    lines.append("}")
    lines.append("")


def gen_rust(schemas) -> str:
    lines = [
        f"//! {HEADER}",
        "#![allow(dead_code)]",
        "",
        "use serde::{Deserialize, Serialize};",
        "use std::collections::BTreeMap;",
        "",
    ]
    for name, topic, version, sch in schemas:
        if topic:
            c = const_name(topic)
            lines.append(f'pub const TOPIC_{c}: &str = "{topic}";')
            lines.append(f"pub const V_{c}: u32 = {version};")
            lines.append("")
        rust_struct(name, sch, lines)
    return "\n".join(lines).rstrip() + "\n"


# -------------------------------------------------------------- Python

def py_type(fld: Field) -> str:
    base = {
        "string": "str",
        "number": "float",
        "integer": "int",
        "boolean": "bool",
        "any": "Dict[str, Any]",
    }.get(fld.kind)
    if fld.kind == "enum":
        base = "Literal[" + ", ".join(json.dumps(v) for v in fld.detail) + "]"
    elif fld.kind == "map":
        base = f"Dict[str, {'float' if fld.detail == 'number' else 'int'}]"
    elif fld.kind == "struct":
        base = f'"{fld.nested_name}"'
    elif fld.kind == "array_struct":
        base = f'List["{fld.nested_name}"]'
    elif fld.kind == "array_scalar":
        inner = {"string": "str", "number": "float", "integer": "int", "boolean": "bool"}
        base = f"List[{inner[fld.detail]}]"
    if fld.nullable or not fld.required:
        return f"Optional[{base}]"
    return base


def py_class(name, schema, topic, version, lines):
    fields, nested = collect_fields(name, schema)
    for sub_name, sub in nested:
        py_class(sub_name, sub, None, None, lines)
    lines.append("@dataclasses.dataclass")
    lines.append(f"class {name}:")
    for fld in fields:
        default = "" if fld.required else " = None"
        lines.append(f"    {fld.name}: {py_type(fld)}{default}")
    if topic:
        lines.append(f"    TOPIC: ClassVar[str] = {json.dumps(topic)}")
        lines.append(f"    V: ClassVar[int] = {version}")
    optional = [f.name for f in fields if not f.required]
    lines.append(f"    _optional: ClassVar[FrozenSet[str]] = frozenset({sorted(optional)!r})")
    lines.append("")
    lines.append("")


PY_HELPERS = '''\
def to_body(obj: Any) -> Dict[str, Any]:
    """Dataclass -> wire dict. Optional-and-absent fields are omitted
    (closed schemas reject null for them); required-nullable stay null."""
    out: Dict[str, Any] = {}
    for f in dataclasses.fields(obj):
        v = getattr(obj, f.name)
        if v is None and f.name in type(obj)._optional:
            continue
        if dataclasses.is_dataclass(v):
            v = to_body(v)
        elif isinstance(v, list):
            v = [to_body(x) if dataclasses.is_dataclass(x) else x for x in v]
        out[f.name] = v
    return out


def from_body(cls: type, body: Dict[str, Any]) -> Any:
    """Wire dict -> dataclass, recursing into nested dataclass fields."""
    hints = typing.get_type_hints(cls)
    kwargs: Dict[str, Any] = {}
    for f in dataclasses.fields(cls):
        if f.name not in body:
            continue
        v = body[f.name]
        t = hints[f.name]
        if typing.get_origin(t) is typing.Union:  # Optional[X]
            args = [a for a in typing.get_args(t) if a is not type(None)]
            t = args[0] if args else t
        if dataclasses.is_dataclass(t) and isinstance(v, dict):
            v = from_body(t, v)
        elif typing.get_origin(t) is list:
            (item,) = typing.get_args(t)
            if dataclasses.is_dataclass(item):
                v = [from_body(item, x) for x in v]
        kwargs[f.name] = v
    return cls(**kwargs)
'''


def gen_python(schemas) -> str:
    lines = [
        f'"""{HEADER}"""',
        "",
        "# flake8: noqa",
        "from __future__ import annotations",
        "",
        "import dataclasses",
        "import typing",
        "from typing import Any, ClassVar, Dict, FrozenSet, List, Literal, Optional",
        "",
        "",
    ]
    for name, topic, version, sch in schemas:
        py_class(name, sch, topic, version, lines)
    lines.append(PY_HELPERS)
    return "\n".join(lines).rstrip() + "\n"


def main():
    schemas = load_schemas()
    outputs = {RUST_OUT: gen_rust(schemas), PY_OUT: gen_python(schemas)}
    if "--check" in sys.argv:
        stale = [
            str(p.relative_to(ROOT))
            for p, want in outputs.items()
            if not p.exists() or p.read_text(encoding="utf-8") != want
        ]
        if stale:
            sys.exit("bindings drift, rerun tools/gen_bindings.py: " + ", ".join(stale))
        print("bindings up to date")
        return
    for p, want in outputs.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(want, encoding="utf-8", newline="\n")
        print(f"wrote {p.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
